App catalog sample node js
OfficeDev/Microsoft-Teams-Samples pull request #101
Opened 2021-05-31 11:58 UTC by Trinetra-MSFT

### Description

This sample app shows how to integrate App Catalog Graph API in Bot and utilize the life cycle of an teams app in Catalog.

**Language Used: nodejs/javascript**

### Proposed Changes
1. Covering List Apps in Catalog all scenario
2. Publishing App to Catalog 
3. Update App in Catalog covering scenario
4. Delete App in Catalog

### Testing
1. Install App Catalog Bot to teams
2. Ping the Bot
Bot will list out supported Action commands
![image](https://user-images.githubusercontent.com/50989436/118778342-9ee83780-b8a7-11eb-93fc-96bf8448e8e0.png)

- listApps

![image](https://user-images.githubusercontent.com/50989436/118778263-8841e080-b8a7-11eb-8499-5892a05e2922.png)

-listAppById
![image](https://user-images.githubusercontent.com/50989436/118778449-bc1d0600-b8a7-11eb-8370-cdd7564f4cd4.png)

-listBotApps
![image](https://user-images.githubusercontent.com/50989436/118778526-cdfea900-b8a7-11eb-91fc-219b4d79098b.png)

- Publish App to Catalog
![image](https://user-images.githubusercontent.com/50989436/118778589-e2db3c80-b8a7-11eb-8159-a7880be1925e.png)

- Update App in Catalog
![image](https://user-images.githubusercontent.com/50989436/118778655-f1295880-b8a7-11eb-9901-cf10e28c006e.png)

- Delete App from Catalog
![image](https://user-images.githubusercontent.com/50989436/118778780-0f8f5400-b8a8-11eb-8353-386de052f324.png)

- Checking the App status
![image](https://user-images.githubusercontent.com/50989436/118778856-246be780-b8a8-11eb-9dcc-b551f1136ecc.png)

2021-05-31 18:05 UTC, Wajeed-msft requested changes

2021-05-31 18:05 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/nodejs/bots/dialogBot.js
> +    async sendUpdateCard(context, cardActions) {
Could you please check and remove if this is not used? Please do the same for other instances if any.

2021-05-31 18:05 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/nodejs/README.md
> +### Descriptions MS TeamsApp resource type
Not sure what does this title means. Could you please clarify or remove if not required?

2021-05-31 18:05 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/nodejs/.env
> +connectionName=
Could you please change this to match casing for other two?

2021-06-01 17:26 UTC, Wajeed-msft approved these changes

2021-06-01 19:51 UTC, asnow003 approved these changes

2021-06-02 04:37 UTC, merged