Details Tab in Meeting csharp
OfficeDev/Microsoft-Teams-Samples pull request #102
Opened 2021-05-31 12:16 UTC by Trinetra-MSFT

## Description

This sample app demonstrate the behavior of Details tab in meeting.

Language Used: C#

### Proposed Changes
1. Added a tab in meeting which basically Adds agenda items to the tab
2. User can add new agenda item
3. it will be added to the tab
4. user can send agenda item in chat
5. Participants in meeting can submit their response to agenda
6. they can also view the collected response in chat or Tab

2021-05-31 18:43 UTC, Wajeed-msft requested changes

2021-05-31 18:43 UTC, Wajeed-msft commented on samples/meetings-details-tab/csharp/DetailsTab/Views/Home/Index.cshtml
> +            taskInfo.url = "https://5a584af2d305.ngrok.io/Detail";
Could you please fetch this from config file?

2021-05-31 18:43 UTC, Wajeed-msft commented on samples/meetings-details-tab/csharp/DetailsTab/Views/Shared/_EmbedPage.cshtml
> +    <meta name="viewport" content="width=device-width" />
Could you please remove this page if it's not used?

2021-05-31 18:43 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/nodejs/README.md
> +Bot Framework v4 AppCatalog sample.
This looks like additional readme file for App Catalog, could you please remove it?

2021-05-31 18:43 UTC, Wajeed-msft commented on samples/meetings-details-tab/csharp/README.md
> +# Official documentation
Could you please add detailed documentation on setting up the samples locally?

2021-06-02 16:34 UTC, Wajeed-msft approved these changes

2021-06-09 14:47 UTC, asnow003 approved these changes

2021-06-09 19:29 UTC, merged