Calling and Meeting Bot
OfficeDev/Microsoft-Teams-Samples pull request #104
Opened 2021-06-14 06:08 UTC by Trinetra-MSFT

##Description
Calling and meeting bot helps to create a call, join a call and transfer/redirect the call. This Bot send a card in chat you can select the action.

Language Used: C#

Attaching the screen recording here to showcase how this bot works

[screen recording](https://microsoftapc-my.sharepoint.com/:v:/g/personal/v-shabid_microsoft_com/ETjN57h7p3ZGqSOlqCCX-bUBT9YQkqIJnKiNWPtuINUL9g?e=bqMMrc)

2021-06-20 11:03 UTC, Wajeed-msft requested changes

2021-06-20 11:03 UTC, Wajeed-msft commented on README.md
> +[calling-meeting-bot#csharp]:samples/calling-meeting-bot/csharp
Could you please move this sample under **samples/bot-calling-meeting/csharp** folder?

2021-06-20 11:03 UTC, Wajeed-msft commented on README.md
Could you please create separate section for Calling and Meeting bots? Please include these two samples as well : https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots#code-sample

2021-06-28 06:42 UTC, Sudhir-MSFT approved these changes

2021-06-28 06:47 UTC, Wajeed-msft approved these changes

2021-06-28 06:47 UTC, merged