Meeting Details tab node js
OfficeDev/Microsoft-Teams-Samples pull request #109
Opened 2021-06-16 14:38 UTC by VivekSharma-MSFT

This sample shows creating poll in meeting , where members of the meeting can answer poll question and can see the results.

2021-06-17 12:03 UTC, Trinetra-MSFT requested changes

2021-06-17 12:03 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/server/api/homeController.js
> +const appID = env.BotId;
Please remove `appId` and `appPassword variable`, You can directly use env.BotId and env.BotPassword in place

2021-06-17 12:03 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/server/api/homeController.js
> +    const client = new ConnectorClient(credentials, { baseUri: ServiceUrl });
`baseUri` it is being set as service URL not as base URL please rename this to serviceURL

2021-06-17 12:03 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/server/api/homeController.js
> +          MicrosoftAppCredentials.trustServiceUrl(ServiceUrl);
Please run eslint to fix space and formatting errors

2021-06-17 12:03 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/server/bot/botActivityHandler.js
> +        const baseUrl = process.env.BaseUrl;
Use process.env.BaseUrl directly rather than assigning it to a variable

2021-06-17 12:03 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/server/services/AdaptiveCardService.js
> +    var template = new ACData.Template(cardJson);
Use `const` here

2021-06-17 12:50 UTC, VivekSharma-MSFT commented on samples/meetings-details-tab/nodejs/appPackage/manifest.json
> +      "configurationUrl": "<<BaseURL>>/ConfigureTab",
No it is not required

2021-06-17 12:51 UTC, VivekSharma-MSFT commented on samples/meetings-details-tab/nodejs/client/.env
> +PORT=4000
Yes it is running on 4000 port

2021-06-17 12:52 UTC, VivekSharma-MSFT commented on samples/meetings-details-tab/nodejs/client/src/components/welcome.js
> +import {v4 as uuidv4  } from "uuid";
It is required to create unique id to identify each poll added

2021-06-18 04:51 UTC, Trinetra-MSFT requested changes

2021-06-18 04:51 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/appPackage/manifest.json
> +  "packageName": "meetingdetailstab",
Please rename this to `com.microsoft.teams.sample.meetingdetailstab`

2021-06-18 04:51 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/server/api/homeController.js
> +    const client = new ConnectorClient(credentials, { baseUri: serviceUrl });
this is still not changed, I can still see `baseUri` in connectorClient, I believe it should be renamed as serviceURL,

2021-06-18 04:53 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/appPackage/manifest.json
> +      "configurationUrl": "<<BaseURL>>/ConfigureTab",
Document says we need to add MeetingDetailsTab in tab configuration context. [https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings#update-your-app-manifest](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings#update-your-app-manifest), Could you please confirm this once by adding it if everything works fine

2021-06-18 04:54 UTC, Trinetra-MSFT commented on samples/meetings-details-tab/nodejs/client/.env
> +PORT=4000
Got it Thanks

2021-06-18 11:53 UTC, Trinetra-MSFT approved these changes

2021-06-20 11:27 UTC, Wajeed-msft requested changes

2021-06-20 11:27 UTC, Wajeed-msft commented on samples/meetings-details-tab/nodejs/Readme.md
> +        ```bash
Is it possible to keep this in a single application host for simplicity of sample code?

2021-06-20 11:27 UTC, Wajeed-msft commented on samples/meetings-details-tab/nodejs/appPackage/manifest.json
> +    "localhost"
Is this required?

2021-06-28 07:49 UTC, Wajeed-msft approved these changes

2021-06-28 07:50 UTC, merged