Tab UI sample - Welcome Tab fixes
OfficeDev/Microsoft-Teams-Samples pull request #1115
Opened 2024-01-18 06:27 UTC by Jegadeesh-MSFT

2024-02-14 09:31 UTC, Pawank-MSFT approved these changes
Looks correct, Approving!

2024-02-14 10:37 UTC, Pawank-MSFT commented
Executed Build pipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/7899922522

2024-02-15 11:54 UTC, Harikrishnan-MSFT requested changes

2024-02-15 11:56 UTC, Jegadeesh-MSFT commented on samples/tab-ui-templates/ts/src/app/static_tabs/welcome.tsx
> +          style={{ marginBottom: "3vh", opacity: ".65", maxWidth: "50rem" }}
will be Fixed in future PR.

2024-02-15 11:56 UTC, Jegadeesh-MSFT commented on samples/tab-ui-templates/ts/src/app/static_tabs/welcome.tsx
> +      <style>
will be Fixed in future PR.

2024-02-15 11:56 UTC, Jegadeesh-MSFT commented on samples/tab-ui-templates/ts/src/app/static_tabs/welcome.tsx
> -          gridGap: "2rem",
will be Fixed in future PR.

2024-02-15 11:57 UTC, merged