Bot configuration - updating the code with latest SDK
OfficeDev/Microsoft-Teams-Samples pull request #1156
Opened 2024-02-20 19:43 UTC by Jegadeesh-MSFT

2024-02-21 06:24 UTC, Pawank-MSFT reviewed
One small comment

2024-02-21 06:24 UTC, Pawank-MSFT commented on samples/bot-configuration-app/nodejs/teamsBot.js
> +    //       config: {
use Multi-line comments.

2024-02-21 09:43 UTC, Jegadeesh-MSFT commented on samples/bot-configuration-app/nodejs/teamsBot.js
> +    //       config: {
Fixed

2024-02-21 21:27 UTC, deekshanya requested changes

2024-02-21 21:27 UTC, deekshanya commented on samples/bot-configuration-app/nodejs/teamsBot.js
I would prefer that option 1 is commented out, while option 2 is not.
also some indentation fixes are needed

2024-02-21 21:27 UTC, deekshanya commented on samples/bot-configuration-app/nodejs/README.md
> +   **Option 2 : Bot Descrption Card:**
nit: description

2024-02-22 16:29 UTC, Jegadeesh-MSFT commented on samples/bot-configuration-app/nodejs/teamsBot.js
Fixed

2024-02-22 16:29 UTC, Jegadeesh-MSFT commented on samples/bot-configuration-app/nodejs/README.md
> +   **Option 2 : Bot Descrption Card:**
Fixed

2024-02-25 06:49 UTC, Prithvi-MSFT approved these changes

2024-02-27 03:54 UTC, deekshanya approved these changes

2024-02-27 06:13 UTC, Jegadeesh-MSFT commented
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/140516784/5dc64ba6-944f-417a-8e7c-ea49deefd9cb)
Build Pipeline executed

https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/8060361180

2024-02-27 09:49 UTC, Pawank-MSFT approved these changes
looks correct, Approving!

2024-02-27 09:59 UTC, merged