SSO Tab C Sharp
OfficeDev/Microsoft-Teams-Samples pull request #12
Opened 2021-01-18 09:29 UTC by Trinetra-MSFT

Added Personal Tab and configurable Tab SSO authentication
Displaying user profile information in Tab
Language : C#

2021-01-20 14:17 UTC, Wajeed-msft requested changes
Please add link to new sample from [Tabs section](https://github.com/OfficeDev/Microsoft-Teams-Samples#tabs-samples) in index page.

2021-01-21 08:24 UTC, Trinetra-MSFT commented
Okay wajeed will be doing this

2021-01-27 06:04 UTC, Trinetra-MSFT commented
Updated Main Index ReadMe for C#

2021-01-28 03:03 UTC, Wajeed-msft approved these changes

2021-02-01 15:42 UTC, asnow003 approved these changes

2021-02-01 16:15 UTC, merged