Conversation Activities from Tab- C# with Razor
OfficeDev/Microsoft-Teams-Samples pull request #129
Opened 2021-08-04 17:58 UTC by v-kalc

* Added ability to start the conversation from tab
* Added ability to continue the conversation from tab
* Added ability to close the conversation from tab

2021-08-05 11:00 UTC, v-chetsh requested changes
Added my comments, please do changes accordingly.

2021-08-06 12:49 UTC, v-chetsh approved these changes
All looks good, approving the PR.

2021-08-06 13:57 UTC, v-kalc commented on README.md
> +|14|Create Conversational tab     | Microsoft Teams tab sample app for demonstrating create conversation tab | [View][tab-conversation#csharp] |           |
Updated

2021-08-06 13:58 UTC, v-kalc commented on samples/tab-conversations/csharp/TabConversation/Pages/configure.cshtml
> +        );
removed

2021-08-06 13:58 UTC, v-kalc commented on samples/tab-conversations/csharp/TabConversation/Properties/launchSettings.json
> +{
we are defining fixed local porting address here

2021-08-06 13:58 UTC, v-kalc commented on samples/tab-conversations/csharp/TabConversation/wwwroot/js/site.js
> +﻿// Please see documentation at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification
removed

2021-08-06 13:58 UTC, v-kalc commented on samples/tab-conversations/csharp/TabConversation/Pages/conversation-tab.cshtml
> +
removed

2021-08-06 13:59 UTC, v-kalc commented on samples/tab-conversations/csharp/TabConversation/Pages/configure.cshtml
> +    function createTabUrl() {
Aligned

2021-08-06 13:59 UTC, v-kalc commented on samples/tab-conversations/csharp/TabConversation/Pages/Index.cshtml.cs
> +        }
removed

2021-08-13 10:34 UTC, Wajeed-msft approved these changes

2021-08-13 10:34 UTC, merged