App in meeting -nodejs
OfficeDev/Microsoft-Teams-Samples pull request #132
Opened 2021-08-13 08:33 UTC by NikitaJain-MSFT

Sample to add a application before, after and during a teams meeting -nodejs.
It covers the following functionality:

Meeting participants can collaborate through added aap in meeting.

2021-08-16 17:00 UTC, v-chetsh requested changes

2021-08-20 01:54 UTC, v-kalc commented on README.md
> +|10|App in meeting | This example shows app to add before, after and during a meting  ||[View][app-in-meeting#js]
Updated

2021-08-20 01:56 UTC, v-kalc commented on samples/app-in-meeting/nodejs/auth.js
> +var Q = require('q');
Inherited from other approved samples need it for specific purpose

2021-08-20 01:56 UTC, v-kalc commented on samples/app-in-meeting/nodejs/static/styles.css
> +  .details {
Added

2021-08-20 01:56 UTC, v-kalc commented on samples/app-in-meeting/nodejs/views/configure.ejs
> +                var radios = document.getElementsByName('notificationType');
updated

2021-08-20 01:57 UTC, v-kalc commented on samples/app-in-meeting/nodejs/views/index.ejs
> +            App in a meeting node js sample
Updated

2021-08-20 01:57 UTC, v-kalc commented on README.md
>  |8|App Localization | Microsoft Teams app localization using Bot and Tab |[View][app-localization#cs]  | [View][app-localization#js]
Added

2021-08-20 01:57 UTC, v-kalc commented on samples/app-in-meeting/nodejs/views/appInMeeting.ejs
> +    $(document).ready(function () {
Added

2021-08-20 01:57 UTC, v-kalc commented on samples/app-in-meeting/nodejs/Manifest/manifest.json
> +    "full": "This example shows app to add before, after and during a meeting"
updated

2021-08-23 04:21 UTC, v-chetsh approved these changes
Changes looks fine, approving the PR.

2021-08-23 09:19 UTC, AbhijeetThakur-msft approved these changes
looks good!

2021-08-24 06:08 UTC, Wajeed-msft requested changes

2021-08-24 09:13 UTC, AbhijeetThakur-msft commented on samples/app-in-meeting/nodejs/Manifest/manifest.json
> +  "id": "<<Manifest-Id>>",
changed

2021-08-24 09:14 UTC, AbhijeetThakur-msft commented on samples/app-in-meeting/nodejs/Manifest/manifest.json
> +        "meetingStage"
removed not required one's

2021-08-24 09:14 UTC, AbhijeetThakur-msft commented on samples/app-in-meeting/nodejs/Readme.md
> +![Stage View Screen](Images/stage_view.png)
done

2021-08-24 09:14 UTC, AbhijeetThakur-msft commented on samples/app-in-meeting/nodejs/Readme.md
> +1. Run ngrok - point to port 3978
done

2021-08-25 06:51 UTC, Wajeed-msft approved these changes

2021-08-25 08:48 UTC, merged