V abt/meeting events
OfficeDev/Microsoft-Teams-Samples pull request #141
Opened 2021-08-30 19:54 UTC by AbhijeetThakur-msft

Sample to show real-time meeting events.

2021-08-31 10:56 UTC, v-chetsh requested changes
Provided my comments.

2021-09-06 02:57 UTC, Wajeed-msft approved these changes

2021-09-06 06:03 UTC, v-chetsh approved these changes
All looks good, approving the PR.

2021-09-06 06:04 UTC, AbhijeetThakur-msft commented
Merging the changes to main.

2021-09-06 06:04 UTC, merged