Message Archive scenario: Bot with RSC permission - C#
OfficeDev/Microsoft-Teams-Samples pull request #160
Opened 2021-09-28 16:05 UTC by NikitaJain-MSFT

Bot with RSC permission can fetch all the messages from a group chat, archive it to text file and send it to user in personal scope.

2021-09-29 07:28 UTC, v-chetsh requested changes
Added my feedback, please look into it.

2021-09-29 07:28 UTC, v-chetsh commented on samples/bot-groupchat-messages-withRSC/csharp/FetchGroupChatMessagesWithRSC/helper/GetChatHelper.cs
> +            }
One line space before it.

Also add summary for all the methods, if required.

2021-09-29 07:28 UTC, v-chetsh commented on samples/bot-groupchat-messages-withRSC/csharp/FetchGroupChatMessagesWithRSC/wwwroot/chat.txt
> +text: <p>hello</p>
Is it required to push this data as well or empty file??

2021-09-29 07:28 UTC, v-chetsh commented on samples/bot-groupchat-messages-withRSC/csharp/README.md
> +﻿﻿﻿Using this C# sample, a bot can receive all channel messages with RSC without @mention.
Please make sure that this readme file is linked with the root readme file.

2021-10-04 07:07 UTC, Wajeed-msft approved these changes

2021-10-04 07:07 UTC, Wajeed-msft commented on README.md
> +[fetchgroupchatmessages#nodejs]:samples/bot-groupchat-messages/nodejs
Could you please rename this to bot-archive-groupchat-messages?

2021-10-04 07:38 UTC, merged