Product Inspection nodejs
OfficeDev/Microsoft-Teams-Samples pull request #181
Opened 2021-10-21 15:07 UTC by NikitaJain-MSFT

App which allows inspecting item and marking it as approved/rejected. Worker will scan the barcode of the product and click picture before marking it as approved/ rejected.

2021-11-01 08:35 UTC, v-chetsh requested changes
Reviewed and provided few comments.

2021-11-01 08:35 UTC, v-chetsh commented on samples/tab-product-inspection/nodejs/Manifest/manifest.json
> +        "entityId": "index",
Why the entity id is "index"??
This tab is related to product inspection so you should give meaningful name.

2021-11-01 08:43 UTC, v-chetsh approved these changes
PR looks fine, approving it.

2021-11-01 10:37 UTC, AbhijeetThakur-msft approved these changes

2021-11-08 04:16 UTC, Wajeed-msft approved these changes

2021-11-08 04:49 UTC, merged