Open sharepoint file in teams file Viewer C#
OfficeDev/Microsoft-Teams-Samples pull request #186
Opened 2021-10-28 17:10 UTC by NikitaJain-MSFT

Bot which shares SharePoint file which can be viewed in Teams file viewer

2021-11-01 14:18 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-11-01 14:18 UTC, v-chetsh commented on README.md
> +|12| Bot with SharePoint file viewer| This sample demos a bot which uploads file to SharePoint site and same files can be viewed in Teams file viewer. | [View][botwithsharepointfileviewer#csharp] |
"Bot with SharePoint file to view in Teams file viewer"

2021-11-01 14:18 UTC, v-chetsh commented on README.md
> +|12| Bot with SharePoint file viewer| This sample demos a bot which uploads file to SharePoint site and same files can be viewed in Teams file viewer. | [View][botwithsharepointfileviewer#csharp] |
This sample demos a bot with capability to upload files to SharePoint site and same files can be viewed in Teams file viewer.

2021-11-01 14:18 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/csharp/BotWithSharePointFileViewer/AppManifest/manifest.json
> +    "full": "This sample demos a bot which uploads file to SharePoint site and same files can be viewed in Teams file viewer"
This sample demos a bot with capability to upload files to SharePoint site and same files can be viewed in Teams file viewer.

2021-11-01 14:18 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/csharp/BotWithSharePointFileViewer/Controllers/SharepointFileUploadController.cs
> +        /// This enpoint is called to save the updated changes for particular product based on id.
endpoint

2021-11-01 14:18 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/csharp/BotWithSharePointFileViewer/SimpleGraphClient.cs
> +                }
Looks like it is not aligned properly.

2021-11-01 14:18 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/csharp/BotWithSharePointFileViewer/helper/SharePointFileHelper.cs
> +        // Get sharepoint file list.
SharePoint

2021-11-01 14:18 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/csharp/README.md
> +﻿﻿﻿Using this C# sample, a bot can upload file to SharePoint site and same files can be viewed in Teams file viewer.
a bot with capability to upload files to SharePoint site and same files can be viewed in Teams file viewer

2021-11-01 16:50 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2021-11-02 07:21 UTC, v-chetsh approved these changes
Changes looks fine, approving the PR.

2021-11-08 04:12 UTC, Wajeed-msft approved these changes

2021-11-08 08:41 UTC, merged