bot-sharepoint-file-viewer nodejs sample
OfficeDev/Microsoft-Teams-Samples pull request #187
Opened 2021-10-29 07:15 UTC by Prithvi-MSFT

Bot which shares SharePoint file which can be viewed in Teams file viewer

2021-11-01 14:10 UTC, v-chetsh requested changes
Reviewed and provided my comments.

2021-11-01 14:10 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/.env
> +SharepointTenantName=
Rename it to SharePointTenantName

2021-11-01 14:10 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/README.md
> +Using this Nodejs sample, a bot can upload file to SharePoint site and same files can be viewed in Teams file viewer.
a bot with capability to upload files to SharePoint site and same files can be viewed in Teams file viewer

2021-11-01 14:10 UTC, v-chetsh commented on README.md
> +|12| Bot with SharePoint file viewer | This sample demos a bot which uploads file to SharePoint site and same files can be viewed in Teams file viewer. ||[View][botfileviewer#js]
This sample demos a bot with capability to upload files to SharePoint site and same files can be viewed in Teams file viewer.

2021-11-01 14:10 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/simpleGraphClient.js
> +    * This endpoin will upload the user's file to SharePoint drive .
endpoint

2021-11-01 14:10 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/simpleGraphClient.js
> +    * This endpoin will upload the user's file to SharePoint drive .
Remove extra space before dot.

2021-11-01 16:54 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-11-01 16:54 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/appPackage/manifest.json
> +    "full": "This sample demos a bot which fetch and archive groupchat messages"
Is this full description correct?

2021-11-01 16:54 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/ssoOauthHelpler.js
> +
Remove extra empty lines

2021-11-01 16:54 UTC, v-chetsh commented on samples/bot-sharepoint-file-viewer/nodejs/appPackage/manifest.json
> +  "manifestVersion": "1.10",
Why have you pushed **sharepoint.zip** file??

2021-11-02 07:21 UTC, v-chetsh approved these changes
Changes looks fine, approving the PR.

2021-11-08 04:13 UTC, Wajeed-msft approved these changes

2021-11-08 05:27 UTC, merged