bot task reminder nodejs
OfficeDev/Microsoft-Teams-Samples pull request #188
Opened 2021-11-08 09:50 UTC by NikitaJain-MSFT

This sample shows feature where user can schedule a task and get reminder on the scheduled date and time.

2021-11-16 08:06 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +- Card with actions `Schedule task`.
This is wrong, action name is "create-reminder"

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +![Schedule task ](Images/ScheduleTaskCard.png)
Contents are wrong:
"Please click here to schedule a recurring task reminder"

![image](https://user-images.githubusercontent.com/59052547/141938646-ebcfda75-dfd7-4483-8dd3-c75e2710ce14.png)

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +![Task Details ](Images/ScheduleTask.png)
This image is wrong:
1) Title is wrong
2) Subtitle should be "Schedula a task"
3) Task Title should be "Task title"
![image](https://user-images.githubusercontent.com/59052547/141938852-441e42bb-3fc7-4be7-8196-cc3854f3fb8b.png)

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +![Task reminder](Images/TaskReminder.png)
Content are wrong:
1) Please click here to schedula a recurring task
2) **"Task submitted successfully, you will get a recurring reminder for the task at a scheduled time"**
3) **"Reminder for a scheduled task!"**
4) There is no space after colon (:)
![image](https://user-images.githubusercontent.com/59052547/141939145-f7f99209-f789-4308-9587-e03418de9a33.png)

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/appPackage/README.md
> +
Is this file required?
If yes, please check and update the contents.

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/appPackage/manifest.json
> +  "version": "1.0.1",
**It should be "version": "1.0.0"**

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/appPackage/manifest.json
> +    "full": "This sample shows feature where user can schedule a task and get reminder on the scheduled date and time."
This sample shows a feature where user can schedule a recurring task and get a reminder on the scheduled time

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/appPackage/manifest.json
> +              "description": "To create reminder for task"
To create the reminder for a task

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/bots/teamsBot.js
> +                }
you can schedule a recurring task and get a reminder on the scheduled time

2021-11-16 08:06 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/views/ScheduleTask.ejs
> +            if (isValid == false) {
Line space before it.

2021-11-16 18:18 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-11-16 18:18 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +![Task Details ](Images/ScheduleTask.png)
Subtitle spelling is wrong here:

![image](https://user-images.githubusercontent.com/59052547/142042296-516c030a-731d-403b-b2e7-a972a6fd85bb.png)

2021-11-16 18:18 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +- Card with actions `Schedule task`.
action

2021-11-16 18:18 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +![Task Details ](Images/ScheduleTask.png)
Task module subtitle spelling is wrong here:
![image](https://user-images.githubusercontent.com/59052547/142042709-343e6a88-3c09-4a69-a08d-4a5e89473ee3.png)

2021-11-17 16:21 UTC, v-chetsh requested changes
Provided feedback

2021-11-17 16:21 UTC, v-chetsh commented on samples/bot-task-reminder/nodejs/Readme.md
> +    ```
Fixed

2021-11-17 16:22 UTC, v-chetsh approved these changes
Changes looks fine, approving the pr.

2021-11-24 05:41 UTC, Wajeed-msft approved these changes

2021-11-24 08:11 UTC, merged