V pritka/bot me message reminder nodejs
OfficeDev/Microsoft-Teams-Samples pull request #195
Opened 2021-11-12 15:56 UTC by Prithvi-MSFT

ME Action which allows sending 1:1 notification with link to the selected message.

2021-11-16 16:14 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +This sample shows feature where user can schedule a task from messaging extension action and get a reminder card at scheduled time.
This sample shows a feature where user can schedule a task from messaging extension action and get a reminder card at a scheduled time.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![Select message](Images/MessageAction.png)
Can you please crop this image and show only relevant section:
![image](https://user-images.githubusercontent.com/59052547/141988044-f48d2b4e-b34a-415d-a80f-23d7d1aeb070.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![Task Details](Images/ScheduleTask.png)
Why the task title is not showing in a textbox like for description ??

![image](https://user-images.githubusercontent.com/59052547/141988280-981381b7-9889-43cb-a891-9a63835c6546.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![Task reminder](Images/TaskReminder.png)
I am not sure why are we passing only Title here without and prefix like 
"**Task with Title:** Development call reminder"

![image](https://user-images.githubusercontent.com/59052547/141988611-d3a12fa9-daf8-4410-80e1-d9e02af37c04.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![Task reminder](Images/TaskReminder.png)
Also there is no proper spacing after colon (:)

![image](https://user-images.githubusercontent.com/59052547/141988724-e11e6c17-daa0-4bff-8772-9958efecbf66.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![Team message action ](Images/MessageActionTeam.png)
Kindly crop this image and add only relevant section here.

![image](https://user-images.githubusercontent.com/59052547/141989005-3847e519-af9a-4e0f-a500-be5e7f7e8c19.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![Team Task Details ](Images/ScheduleTaskTeam.png)
Similar image at above, you are using Textbox for description and not in Title.
But here I can't see the text boxes properly.

Could you please update the UI properly.
![image](https://user-images.githubusercontent.com/59052547/141989287-190fb5a3-b76d-4f51-bf8a-48389d537ee2.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +![ TeamTask reminder](Images/TaskReminderTeam.png)
You can mark Title and subtitle in bold to differentiate and also add space after colon (:)
![image](https://user-images.githubusercontent.com/59052547/141989481-db2c11f4-72b9-462a-913d-46cab426932b.png)

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/Readme.md
> +2) In a terminal, navigate to `samples/bot-message-reminder/nodejs`
Which terminal??
Where will the user open the code in VS or VS Code and how?

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/appPackage/README.md
> +# App Package
Is this file required??

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/appPackage/manifest.json
> +    "short": "Message reminder from ME",
Message reminder using messaging extension

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/appPackage/manifest.json
> +    "full": "Message reminder from ME"
Message reminder setup through messaging extension action command.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/appPackage/manifest.json
> +    "short": "Message reminder from ME",
Message reminder setup through messaging extension action command

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/appPackage/manifest.json
> +    "full": "This sample shows feature where user can schedule a task from messaging extension action and get a reminder card at scheduled date and time."
This sample shows a feature where user can schedule a task from messaging extension action and get a reminder card at a scheduled date and time.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/bots/teamsBot.js
> +            for (let member = 0; member < membersAdded.length; member++) {
One line space before it.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/models/taskModuleResponseFactory.js
> +        if (typeof taskModuleInfoOrString === 'string') {
One line space before it.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/views/ScheduleTask.ejs
> +            microsoftTeams.initialize(()=>{
One line space before it.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/views/ScheduleTask.ejs
> +                if(description == "") {
One line space before it.

2021-11-16 16:14 UTC, v-chetsh commented on samples/bot-message-reminder/nodejs/views/ScheduleTask.ejs
> +                if (isValid == false) {
One line space before it.

2021-11-17 16:40 UTC, v-chetsh approved these changes
Changes looks fine approving the PR.

2021-11-24 05:50 UTC, Wajeed-msft commented on README.md
> +[memessagereminder#nodejs]:samples/bot-message-reminder/nodejs
Please renmae the folde to msgext-message-reminder. Please do the same for node project.

2021-11-24 05:53 UTC, Wajeed-msft approved these changes

2021-11-24 05:53 UTC, Wajeed-msft commented on README.md
> +[memessagereminder#nodejs]:samples/bot-message-reminder/nodejs
Please renmae the folde to msgext-message-reminder.

2021-11-24 05:53 UTC, Wajeed-msft commented on samples/bot-message-reminder/nodejs/Readme.md
> +## Message reminder with messaging extension action
1. Add SEO metadata.
2. Keep header with single #
3. Keep only first three images.

2021-11-24 07:50 UTC, merged