Bot-task-approval nodejs sample
OfficeDev/Microsoft-Teams-Samples pull request #212
Opened 2021-12-06 06:01 UTC by Prithvi-MSFT

2021-12-07 11:12 UTC, v-chetsh requested changes
Reviewed and provided my comments.

2021-12-07 11:12 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/bots/teamsBot.js
> +
Remove empty line

2021-12-07 11:12 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/services/taskService.js
> +        tasks = storageService.storeFetch(incKey);
Blank line  before it.

2021-12-07 11:12 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/services/taskService.js
> +        tasks = storageService.storeFetch(incKey);
Blank line before and after of it.

2021-12-07 11:12 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/services/taskService.js
> +    }
Blank line before and after of it.

2021-12-07 11:12 UTC, v-chetsh commented on samples/bot-task-approval/nodejs/Readme.md
> +---
Why you have 2 Readme.md files ??
1) samples/bot-request-approval/nodejs/Readme.md
2) samples/bot-task-approval/nodejs/Readme.md

2021-12-07 11:12 UTC, v-chetsh commented on samples/bot-task-approval/nodejs/appPackage/manifest.json
> +﻿{
Why 2 manifest files??

2021-12-09 09:10 UTC, v-chetsh requested changes
Reviewed and provided comments.

2021-12-09 09:10 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +# Send task request using universal adaptive cards in group chat
**Universal Adaptive Cards**

2021-12-09 09:10 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +- Note: Only user who created the card will see the buttons to edit and cancel the request.
This should come in next line:
![image](https://user-images.githubusercontent.com/59052547/145363727-d197b78a-cadd-465c-ab09-7eabdf21d71e.png)

2021-12-09 09:10 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +---
Your complete project is not showing properly in samples folder:
![image](https://user-images.githubusercontent.com/59052547/145367101-b1de5ba1-89b9-44eb-9c4c-d00141c2fe3e.png)

2021-12-13 16:41 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +1. Requester : Can request for any task approval from manager by intiating request in groupchat using bot command `request` and only requester can edit the request card.
initiating a request in group chat

2021-12-13 16:42 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +2. Manager : Can see the request raised by user in the same groupchat with an option of approve or reject.
group chat

2021-12-13 16:44 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +- Note: Only the manager of the request will see the buttons to approve/reject the request.
Manager of the task request will only be able to see the buttons to approve or reject the request.

2021-12-13 16:45 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +- If manager approves or rejects the request card will be refreshed for all the members in groupchat.
If manager approves or rejects the request, card will be refreshed for all the members in group chat.

2021-12-13 16:45 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +- Other members will only able to see details of the created request.
Other members will only be able to see the details of the created request.

2021-12-13 16:47 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +**Note:** App should be installed for user's manager also to get task approval notification.
App should be installed for user's manager as well, so that manager can get the task approval notification.

2021-12-13 17:19 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2021-12-15 05:59 UTC, Wajeed-msft approved these changes

2021-12-15 06:00 UTC, merged