Typeahead Search for adaptive cards C# sample
OfficeDev/Microsoft-Teams-Samples pull request #216
Opened 2021-12-14 13:55 UTC by Prithvi-MSFT

2021-12-23 06:29 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +description: Demonstrating feature of type ahead search (static and dynamic) control in Adaptive cards.
Demonstrating the feature of type ahead search (static and dynamic) control in Adaptive Cards.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +This sample shows feature of type ahead search (static and dynamic) control in Adaptive cards.
This sample shows the feature of type ahead search (static and dynamic) control in Adaptive Cards.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +    "short": "Search adaptive card",
Type ahead search on Adaptive Card

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +    "short": "Search control adaptive card",
Type ahead search on Adaptive Card

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +    "full": "This sample shows feature type ahead search (static and dynamic) control in adaptive cards."
This sample shows the feature of type ahead search (static and dynamic) control on Adaptive Cards.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +              "description": "To get static search card"
To get static type ahead search Adaptive Card

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +              "description": "To get dynamic search card"
To get dynamic type ahead search Adaptive Card

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +page_type: sample
Please link this readme file with root folder readme file.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs
> +                InvokeResponse adaptiveCardResponse;
Unused variable, please remove it.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs
> +                var itemList = packages.Select(item => { var obj = new { Title = item.Item1, Value = item.Item2 }; return obj; }).ToList();
What is itemList ?
Rename it properly

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Cards/DynamicSearchCard.json
> +  "version": "1.2"
Put these 2 lines at top.

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Cards/StaticSearchCard.json
> +  "version": "1.2"
Put these 2 lines at top

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Models/RequestDetails.cs
> +    }
Why do we need this model??

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Startup.cs
> +            services.AddSingleton<IStorage, MemoryStorage>();
Where are we using this storage?

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +# Type ahead search control in Adaptive cards
Type ahead search control on Adaptive Cards

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +![static search card](Images/staticSearchCard.png)
Images are not displaying properly on UI

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +![dynamic search card](Images/dynamicSearchCard.png)
Images are not displaying properly on UI

2021-12-23 06:29 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +   - Your app must be registered in the Azure AD portal. See [Register an application with the Microsoft identity platform](https://docs.microsoft.com/en-us/graph/auth-register-app-v2).
Do we need Auth SSO for this sample?

2021-12-23 08:48 UTC, v-chetsh commented on README.md
> +[typeaheadsearch#csharp]:samples/type_ahead_search_adaptive_cards/csharp
Why underscore (_), we have used hyphen (-) for all other sample names ?

2021-12-23 08:49 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +description: Demonstrating the feature of type ahead search (static and dynamic) control in Adaptive Cards.
control on Adaptive Cards

2021-12-23 08:50 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/README.md
> +This sample shows the feature of type ahead search (static and dynamic) control in Adaptive Cards.
control on Adaptive Cards

2021-12-23 08:52 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +    "short": "Typeahead search Adaptive Card",
Typeahead search on Adaptive Card

2021-12-23 08:53 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +    "full": "Adaptive card with search control"
Adaptive Card with type ahead search control

2021-12-23 08:54 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/AppPackage/manifest.json
> +    "short": "Typeahead search Adaptive Card",
Typeahead search on Adaptive Card

2021-12-23 08:56 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs
> +                    return adaptiveCardResponse;
Alignment is not correct

2021-12-23 08:56 UTC, v-chetsh commented on samples/type_ahead_search_adaptive_cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs
> +                var data = new
What is data variable here, please add meaningful name

2021-12-23 10:52 UTC, v-chetsh approved these changes
Changes looks fine, approving the PR.

2021-12-24 06:40 UTC, Wajeed-msft requested changes

2021-12-24 06:40 UTC, Wajeed-msft commented on samples/type-ahead-search-adaptive-cards/csharp/README.md
> +page_type: sample
Let's follow the correct naming convention.  Please update the folder and make sure changes are reflected in ReadMe and Deployment scripts.

samples/bot-type-ahead-search-adaptive-cards

2021-12-24 06:40 UTC, Wajeed-msft commented on samples/type-ahead-search-adaptive-cards/csharp/TypeaheadSearch/Bots/ActivityBot.cs
> +                };
Let's check handle following scenarios.

1. No results  (204). 
2. Internal Server Errors (500)

2021-12-24 17:11 UTC, v-chetsh requested changes
Reviewed and provided my comments.

2021-12-24 17:11 UTC, v-chetsh commented on samples/bot-type-ahead-search-adaptive-cards/csharp/README.md
> +This sample shows the feature of type ahead search (static and dynamic) control on Adaptive Cards.
We did not mentioned that how are we going to get these static or dynamic cards??

2021-12-24 17:11 UTC, v-chetsh commented on samples/bot-type-ahead-search-adaptive-cards/csharp/README.md
> +`Static search`
Also explain a bit more on how static and dynamic search works?

2021-12-24 17:11 UTC, v-chetsh commented on samples/bot-type-ahead-search-adaptive-cards/csharp/README.md
> +![dynamic search card](TypeaheadSearch/Images/dynamicSearchCard.png)
We did not mentioned that how are we going to get these static or dynamic cards??

2021-12-24 17:11 UTC, v-chetsh commented on samples/bot-type-ahead-search-adaptive-cards/csharp/README.md
> +`Dynamic search`
Also explain a bit more on how static and dynamic search works?

2021-12-24 17:11 UTC, v-chetsh commented on samples/bot-type-ahead-search-adaptive-cards/csharp/README.md
> +`Dynamic search results`
We have "Submit" button on card so what will happen once we submit it??
Mention in doc for it.

2021-12-27 08:34 UTC, v-chetsh approved these changes
Changes looks fine, approving the PR.

2021-12-27 10:41 UTC, Wajeed-msft approved these changes

2021-12-29 18:09 UTC, merged