Readme file changes for adding teams channel in bot
OfficeDev/Microsoft-Teams-Samples pull request #222
Opened 2021-12-24 08:09 UTC by Prithvi-MSFT

Added steps for enabling teams channel in bot registration.

2021-12-31 18:23 UTC, v-chetsh requested changes
Reviewed and provided my feedback.

2021-12-31 18:23 UTC, v-chetsh commented on samples/app-auth/nodejs/README.md
>  1. While registering the bot, use `https://<your_ngrok_url>/api/messages` as the messaging endpoint.
Why this is added as a point 1. ?
Also I can see that the next point is also starting with 1. 
![image](https://user-images.githubusercontent.com/59052547/147834857-f5c22723-ada1-4e90-ad25-a733757c5034.png)

2021-12-31 18:23 UTC, v-chetsh commented on samples/bot-request-approval/nodejs/Readme.md
> +- Ensure that you've [enabled the Teams Channel](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0)### 2. Run your bot sample
Is this correct here?
"### 2. Run your bot sample"

![image](https://user-images.githubusercontent.com/59052547/147835269-582b09d4-f9aa-4f0a-924f-9e7089dd2809.png)

2022-01-03 08:48 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2022-01-03 09:08 UTC, Wajeed-msft approved these changes

2022-01-03 09:12 UTC, merged