Incoming webhook c# saample
OfficeDev/Microsoft-Teams-Samples pull request #225
Opened 2022-01-05 05:21 UTC by Prithvi-MSFT

2022-01-09 17:50 UTC, AbhijeetThakur-msft commented on samples/incoming-webhook/csharp/IncomingWebhook/ClientApp/README.md
> +# Getting Started with Create React App
we can remove this Readme file

2022-01-09 17:50 UTC, AbhijeetThakur-msft commented on samples/incoming-webhook/csharp/IncomingWebhook/ClientApp/src/components/configure-message.tsx
> +
try to add comments to the methods

2022-01-09 17:50 UTC, AbhijeetThakur-msft commented on samples/incoming-webhook/csharp/IncomingWebhook/Startup.cs
> +            //app.UseMvc();
Please remove commented code if not required

2022-01-09 17:50 UTC, AbhijeetThakur-msft commented on samples/incoming-webhook/csharp/README.md
> +This sample illustrates usage of incoming webhook.
Please add more details, like the editor part and action usage.

2022-01-09 17:50 UTC, AbhijeetThakur-msft commented on samples/incoming-webhook/csharp/README.md
> +2) Clone the repository
The numbering should start with 1)

2022-01-10 07:40 UTC, AbhijeetThakur-msft commented on samples/incoming-webhook/csharp/README.md
> +page_type: sample
this format is broken, please check once.
![image](https://user-images.githubusercontent.com/86800431/148731913-b7d56a9e-14ab-4835-a756-208b3bf7c560.png)

2022-01-10 08:23 UTC, AbhijeetThakur-msft approved these changes

2022-01-14 05:03 UTC, Wajeed-msft requested changes

2022-01-14 05:03 UTC, Wajeed-msft commented on samples/incoming-webhook/csharp/README.md
> +   - Select Add to meeting in the pop-up dialog box. Your app is uploaded to Teams.
Please correct  this. This sample is not supported for meeting scenarios.

2022-01-14 05:03 UTC, Wajeed-msft commented on samples/incoming-webhook/csharp/README.md
> +1) Create a incoming webhook. [Create incoming webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
```suggestion
1) Create a incoming webhook. [Create incoming webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook). Keep this webhook URL handy while running the sample. 
```

2022-01-14 05:03 UTC, Wajeed-msft commented on samples/incoming-webhook/csharp/README.md
> +7) Run the app from a terminal or from Visual Studio, choose option A or B.
After step 7, let's add one or two steps which talk about trying out the sample.

2022-01-14 05:03 UTC, Wajeed-msft commented on samples/incoming-webhook/csharp/README.md
> +- [Bot Framework Documentation](https://docs.botframework.com)
Let's link to Connector sections instead of Bot.

2022-01-17 06:45 UTC, Wajeed-msft approved these changes

2022-01-17 09:55 UTC, merged