Added sdk support methods and new tab for youtube video
OfficeDev/Microsoft-Teams-Samples pull request #232
Opened 2022-01-20 08:05 UTC by Prithvi-MSFT

2022-01-22 19:15 UTC, AbhijeetThakur-msft requested changes

2022-01-22 19:15 UTC, AbhijeetThakur-msft commented on samples/tab-adaptive-cards/csharp/TabWithAdpativeCardFlow/Bots/ActivityBot.cs
> +                return null;
IS this null return required?

2022-01-24 09:40 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2022-01-25 07:47 UTC, Wajeed-msft requested changes
Could you please update the [ReadMe.md](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/v-pritka/tab-adaptive-cards/samples/tab-adaptive-cards/csharp/README.md) to include one screenshot at top?

2022-01-25 14:36 UTC, Wajeed-msft approved these changes

2022-01-25 14:38 UTC, Wajeed-msft approved these changes

2022-01-30 15:30 UTC, AbhijeetThakur-msft approved these changes

2022-01-30 15:30 UTC, merged