Link unfurling meeting sample
OfficeDev/Microsoft-Teams-Samples pull request #261
Opened 2022-03-02 19:07 UTC by juna-gupta

This sample illustrates a common scenario where a user shares a link to a resource (dashboard in this sample) with a group of users, and they collaborate to review it in a meeting.

2022-03-04 18:36 UTC, Wajeed-msft requested changes
Could you please make following changes?
1. Move the solution under language specific folder i.e. ~/samples/msgext-link-unfurling-meeting/**csharp** folder.
2. Add entry for this solution from [Messaging Extensions samples](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/samples/linkunfurlingmeeting#messaging-extensions-samples-using-the-v4-sdk) section.
3. Update [root ReadMe file](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/samples/linkunfurlingmeeting/samples/msgext-link-unfurling-meeting/README.md) to include meta data so that it's discoverable in [sample code browser](https://docs.microsoft.com/en-us/samples/browse/?products=office-teams). 
**Example metadata** [graph-app-installation-lifecycle](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/samples/linkunfurlingmeeting/samples/graph-app-installation-lifecycle/csharp)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/31851992/156821517-8cd7ba63-16ec-408c-83b0-cc72df7f94a0.png">

2022-03-04 19:53 UTC, juna-gupta commented
> Could you please make following changes?
> 
> 1. Move the solution under language specific folder i.e. ~/samples/msgext-link-unfurling-meeting/**csharp** folder.
> 2. Add entry for this solution from [Messaging Extensions samples](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/samples/linkunfurlingmeeting#messaging-extensions-samples-using-the-v4-sdk) section.
> 3. Update [root ReadMe file](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/samples/linkunfurlingmeeting/samples/msgext-link-unfurling-meeting/README.md) to include meta data so that it's discoverable in [sample code browser](https://docs.microsoft.com/en-us/samples/browse/?products=office-teams).
>    **Example metadata** [graph-app-installation-lifecycle](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/samples/linkunfurlingmeeting/samples/graph-app-installation-lifecycle/csharp)
> 
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/31851992/156821517-8cd7ba63-16ec-408c-83b0-cc72df7f94a0.png">

Addressed in the latest iteration.

2022-03-04 21:59 UTC, aosolis approved these changes

2022-03-06 11:02 UTC, Wajeed-msft approved these changes

2022-03-07 18:21 UTC, merged