Map aad sso with facebook and google csharp sample
OfficeDev/Microsoft-Teams-Samples pull request #263
Opened 2022-03-04 07:29 UTC by Prithvi-MSFT

2022-03-05 18:28 UTC, AbhijeetThakur-msft requested changes

2022-03-05 18:28 UTC, AbhijeetThakur-msft commented on samples/aad-sso-map/csharp/README.md
> +   In Azure portal, create a [Bot Framework registration resource](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Caadv2).
Change this section to Azure Bot service.

2022-03-05 18:28 UTC, AbhijeetThakur-msft commented on samples/aad-sso-map/csharp/README.md
> +page_type: sample
Make sure to add sample name in root Readme file as app-

2022-03-07 06:00 UTC, AbhijeetThakur-msft approved these changes

2022-03-07 06:01 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2022-03-07 06:22 UTC, Wajeed-msft approved these changes

2022-03-07 09:12 UTC, merged