Identity linking with aad sso nodejs
OfficeDev/Microsoft-Teams-Samples pull request #264
Opened 2022-03-04 15:47 UTC by NikitaJain-MSFT

2022-03-05 18:23 UTC, AbhijeetThakur-msft requested changes

2022-03-05 18:23 UTC, AbhijeetThakur-msft commented on README.md
> +[identity-link-with-sso#nodejs]:samples/identity-link-with-sso/nodejs
Let's change the folder name as per the capability, here we can use app- as we are using multiple capabilities.

2022-03-05 18:23 UTC, AbhijeetThakur-msft commented on samples/identity-linking-with-sso/nodejs/README.md
> +This sample demos linking aad id with  facebook and google account of user in bot, ME and tab.
This sample demos linking user's AAD id with Facebook and google account of user from bot, ME and tab.

2022-03-05 18:23 UTC, AbhijeetThakur-msft commented on samples/identity-linking-with-sso/nodejs/README.md
> +15. Create a Bot Registration
Let's change this to Azure Bot Service

2022-03-05 18:23 UTC, AbhijeetThakur-msft commented on samples/identity-linking-with-sso/nodejs/README.md
> +   In Azure portal, create a [Bot Framework registration resource](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp%2Caadv2).
Please change this to Azure Bot service.

2022-03-07 05:49 UTC, AbhijeetThakur-msft approved these changes

2022-03-07 05:55 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2022-03-07 06:23 UTC, Wajeed-msft approved these changes

2022-03-07 06:39 UTC, merged