Staggered permission node
OfficeDev/Microsoft-Teams-Samples pull request #265
Opened 2022-03-05 13:58 UTC by NikitaJain-MSFT

2022-03-05 18:14 UTC, AbhijeetThakur-msft requested changes

2022-03-05 18:14 UTC, AbhijeetThakur-msft commented on README.md
> +|16| Tab staggered permission | Demonstrating a feature to get staggered graph api permissions. ||[View][staggeredpermissions#nodejs]|
This is not same as in csharp sample.

2022-03-07 05:48 UTC, AbhijeetThakur-msft approved these changes

2022-03-07 05:56 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2022-03-07 06:24 UTC, Wajeed-msft approved these changes

2022-03-07 06:53 UTC, merged