Live coding interview using Shared meeting stage - Nodejs
OfficeDev/Microsoft-Teams-Samples pull request #288
Opened 2022-03-21 15:39 UTC by NikitaJain-MSFT

2022-03-24 07:49 UTC, AbhijeetThakur-msft requested changes

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/App.test.js
> +import { render, screen } from '@testing-library/react';
Does this test pass?

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/App.tsx
> +        <Suspense fallback={<div></div>}>
for fallback, user will not know what happened, if needed provide some message.

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/components/question.tsx
> +    const questionNumber = params['srno'];
rename this srno to questionId as this is not meanigfull

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/components/question.tsx
> +    const debounce = (callback: any, lim: any) => {
rename this to give proper understanding and avoid short forms.

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/components/question.tsx
> +                if (question.srNo == questionNumber) {
rename srno to questionId or questionNo

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/components/tab.css
> +.text-label {
check if these all classes are being used.

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/components/tab.tsx
> +
remove this extra space.

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/types/question.ts
> +export const IQuestionDetails = {
Provide some comments on what is this used for.

2022-03-24 07:49 UTC, AbhijeetThakur-msft commented on README.md
>  [app-hello-world#ts]:samples/app-hello-world/nodejs
Please make sure we do not have any horizonal scroll bar in any screen.

2022-03-24 19:58 UTC, eoinobrien commented on samples/meetings-live-code-interview/nodejs/api/package.json
> +  "description": "Sequential Workflows in adaptive card",
Can we update this to something accurate?

2022-03-31 06:48 UTC, NikitaJain-MSFT commented on samples/meetings-live-code-interview/nodejs/ClientApp/src/types/question.ts
> +        }
as per requirements we do not need to add configurable questions.

2022-03-31 09:05 UTC, v-chetsh approved these changes
Changes looks fine for me, approving it.

2022-04-04 08:49 UTC, Wajeed-msft approved these changes

2022-04-04 08:53 UTC, AbhijeetThakur-msft approved these changes

2022-04-04 09:06 UTC, merged