People picker in tab
OfficeDev/Microsoft-Teams-Samples pull request #300
Opened 2022-04-07 15:31 UTC by NikitaJain-MSFT

2022-04-08 07:14 UTC, v-chetsh reviewed
Reviewed and provided my feedback.

2022-04-08 07:14 UTC, v-chetsh commented on samples/tab-people-picker/nodejs/Manifest/manifest.json
> +  "version": "1.0.1",
1.0.0

2022-04-08 07:14 UTC, v-chetsh commented on samples/tab-people-picker/nodejs/Manifest/manifest.json
> +  ],
Looks like alignment is not correct.

2022-04-08 07:14 UTC, v-chetsh commented on samples/tab-people-picker/nodejs/Readme.md
> +createdDate: "06-10-2021 01:48:56"
This date is wrong.

2022-04-08 07:14 UTC, v-chetsh commented on samples/tab-people-picker/nodejs/views/configure.ejs
> +<script src="https://statics.teams.cdn.office.net/sdk/v1.10.0/js/MicrosoftTeams.min.js" integrity="sha384-6oUzHUqESdbT3hNPDDZUa/OunUj5SoxuMXNek1Dwe6AmChzqc6EJhjVrJ93DY/Bv" crossorigin="anonymous"></s
Let's put these on top.

2022-04-08 07:14 UTC, v-chetsh commented on samples/tab-people-picker/nodejs/views/index.ejs
> +            Graph activity feed notification node js sample
This is not Graph activity feed sample

2022-04-08 09:26 UTC, AbhijeetThakur-msft requested changes

2022-04-08 09:26 UTC, AbhijeetThakur-msft commented on README.md
> +|18| Tab people picker | This is an tab app which shows the feature of client sdk people picker. ||[View][tab-people-picker#nodejs]|
Let's rename this as : This sample shows tab capability with ...

2022-04-08 09:26 UTC, AbhijeetThakur-msft commented on samples/tab-people-picker/nodejs/views/tab.ejs
> +        content="default-src *; style-src 'self' 'unsafe-inline' http://localhost:3978; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
Let's check for this static url.

2022-04-12 08:57 UTC, AbhijeetThakur-msft approved these changes

2022-04-13 11:51 UTC, v-chetsh approved these changes
Changes looks fine, approving it.

2022-04-27 04:54 UTC, Wajeed-msft approved these changes

2022-05-06 07:02 UTC, merged