[Graph Life cycle]: Added channel life cycle sample code using Microsoft Graph API
OfficeDev/Microsoft-Teams-Samples pull request #31
Opened 2021-02-17 05:00 UTC by Trinetra-MSFT

## Description
This sample demonstrate the life cycle of a channel using Microsoft Graph API.
Following channels API is integrated in the sample
`Create Channel`
`Delete Channel`
`Update Channel`
`Get Channel`
`Create Tab`
`Display Members of a channel`

**Language Used:** C#

## Testing

We have created one configurable tab to demo channel life cycle, Tab contains the all the above mentioned scenarios for the channel
![image](https://user-images.githubusercontent.com/50989436/108158475-00fb9a00-710b-11eb-88e3-84bd74f18ba8.png)

![image](https://user-images.githubusercontent.com/50989436/108158499-0e188900-710b-11eb-9ce2-4d59cbcd696e.png)

![image](https://user-images.githubusercontent.com/50989436/108158454-f5a86e80-710a-11eb-9358-3c51e53301f7.png)

2021-02-22 10:04 UTC, Wajeed-msft requested changes
Add link to sample in root readme file. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-trkum/channelLifeCycle#graph-apis

2021-02-22 10:06 UTC, Wajeed-msft commented on samples/graph-channel-lifecycle/csharp/README.md
> +   git clone https://github.com/VaraPrasad-MSFT/ChannelLifecycle.git
Please correct this.

2021-02-23 04:48 UTC, Trinetra-MSFT commented on samples/graph-channel-lifecycle/csharp/README.md
> +   git clone https://github.com/VaraPrasad-MSFT/ChannelLifecycle.git
DOne

2021-02-24 03:30 UTC, Wajeed-msft approved these changes

2021-02-24 16:12 UTC, asnow003 approved these changes

2021-02-24 16:21 UTC, merged