Add a new proactive tab conversations using a bot proof of concept
OfficeDev/Microsoft-Teams-Samples pull request #351
Opened 2022-05-25 20:05 UTC by eoinobrien

This proof of concept showcases how an external service can create a conversation in a channel that in turn can be opened in a [conversational tab](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/conversational-tabs).

2022-06-02 21:30 UTC, eoinobrien commented on samples/bot-tab-conversations/csharp/Source/ConversationalTabs.Web/ClientApp/src/routes/InquirySubEntityTab.tsx
> +      microsoftTeams.conversations.openConversation({
# Open the conversation tab
With this conversation ID, we use the Teams SDK to open the conversation in the sidebar

2022-06-24 17:24 UTC, aosolis approved these changes

2022-06-30 04:29 UTC, Wajeed-msft requested changes

2022-06-30 04:29 UTC, Wajeed-msft commented on samples/bot-tab-conversations/csharp/Source/ConversationalTabs.Web/Manifest/manifest.json
> +  "validDomains": ["localhost:44326", "*.ngrok.io"],
We can remove localhost valid domain if we are not loading it in Teams.

2022-07-21 05:16 UTC, Wajeed-msft approved these changes

2022-07-21 12:49 UTC, merged