Task-module dev preview changes
OfficeDev/Microsoft-Teams-Samples pull request #360
Opened 2022-06-03 18:52 UTC by HunaidHanfee-MSFT

[Meeting details tab c#](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-details-tab/csharp) (Pending for PR 3)
[Meeting details tab node](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-details-tab/nodejs) (Pending for PR 3)
[App task module c#](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-task-module)
[App task module node](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-task-module/nodejs)
[Meeting content bubble node](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-content-bubble/nodejs)
[Mgext-link-unfurling c#](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-link-unfurling-meeting/csharp)

2022-06-04 12:45 UTC, v-chetsh requested changes
Reviewed and provided my comments.

2022-06-04 12:45 UTC, v-chetsh commented on samples/app-task-module/csharp/Microsoft.Teams.Samples.TaskModule.Web/Views/Home/Tasks.cshtml
> +                microsoftTeams.tasks.startTask(taskCardInfo, submitHandler);
I think, we should use **"dialog.open"** rather than tasks.startTask ??

2022-06-04 12:45 UTC, v-chetsh commented on samples/app-task-module/nodejs/src/TaskModuleTab.ts
> +                            microsoftTeams.tasks.startTask(taskCardInfo, submitHandler);
I think, we should use "microsoftTeams.dialog.open"

2022-06-04 12:45 UTC, v-chetsh commented on samples/app-task-module/nodejs/src/TaskModuleTab.ts
> +                            microsoftTeams.tasks.startTask(taskCardInfo);
Check if we can use "microsoftTeams.dialog.open"

2025-07-25 06:38 UTC, Pawank-MSFT commented
Closing because PR is too much old and functionality is not supporting.

2025-07-25 06:38 UTC, closed without merging