Sample showcasing context object for private/shared channels in tab
OfficeDev/Microsoft-Teams-Samples pull request #369
Opened 2022-06-17 07:54 UTC by Prithvi-MSFT

2022-06-28 13:45 UTC, ChetanSharma-msft commented on samples/tab-channel-context/nodejs/ClientApp/src/components/constants/tab-constants.ts
> +export const tabHeaderPublicChannel = "Current tab is loaded in regular channel";
regular => public

2022-06-28 13:55 UTC, ChetanSharma-msft commented on samples/tab-channel-context/nodejs/README.md
> +
Add pre-requisite steps to create private or regular channels with reference doc links.

2022-06-28 13:55 UTC, ChetanSharma-msft commented on samples/tab-channel-context/nodejs/README.md
> +description: "This sample shows the contents of context object in a private and shared channel."
contents of tab context object

2022-06-28 13:55 UTC, ChetanSharma-msft commented on samples/tab-channel-context/nodejs/README.md
> +This sample shows the contents of context object in a private and shared channel.
contents of tab context object

2022-06-29 15:52 UTC, ChetanSharma-msft requested changes
Reviewed and provided my comments

2022-06-29 15:56 UTC, ChetanSharma-msft requested changes
Added my comments

2022-06-29 15:56 UTC, ChetanSharma-msft commented on samples/tab-channel-context/nodejs/README.md
> +This sample shows the contents of tab context object in a private and shared channel.
Add a prerequisite for creating private and shared channel.
Also, add the doc link to create private or shared channel.
Mention that steps to add the tab in private/shared channel.

2022-06-29 16:53 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-03 12:54 UTC, Wajeed-msft approved these changes

2022-07-03 12:54 UTC, Wajeed-msft commented on samples/tab-channel-context/nodejs/README.md
> +
Can we add screenshot for Shared Channel as well? 
Also, mark it as public channel instead of regular channel.

2022-07-05 06:45 UTC, merged