Meetings Live Caption POC - C#
OfficeDev/Microsoft-Teams-Samples pull request #376
Opened 2022-06-22 18:00 UTC by HunaidHanfee-MSFT

2022-06-28 04:15 UTC, AbhijeetThakur-msft requested changes

2022-06-28 04:15 UTC, AbhijeetThakur-msft commented on samples/meetings-live-caption/csharp/README.md
> +This is a sample meeting side panel application which demonstrates how to enable live caption in the meeting and using the CART link how to send caption in live meeting. Meeting side panel applicatio
Please add one hero image at the top, other images can remain at bottom.

2022-06-28 04:15 UTC, AbhijeetThakur-msft commented on samples/meetings-live-caption/csharp/README.md
> +- Open ngrok and run command `ngrok http -host-header=rewrite 3978`
Cloning the repo step is missing. Also please check the order with previous samples.

2022-06-30 06:38 UTC, Wajeed-msft approved these changes

2022-06-30 06:43 UTC, ChetanSharma-msft commented on samples/meetings-live-caption/csharp/MeetingLiveCaption/AppManifest/manifest.json
> +  "id": "<<GUID ID>>",
Rename it as AppId and also change in Readme file.

2022-06-30 08:16 UTC, AbhijeetThakur-msft approved these changes

2022-06-30 08:17 UTC, merged