Changed the live-coding sample to use the live share sdk nodejs
OfficeDev/Microsoft-Teams-Samples pull request #381
Opened 2022-06-27 04:41 UTC by Prithvi-MSFT

2022-06-29 17:03 UTC, ChetanSharma-msft commented on samples/meetings-live-code-interview/nodejs/appPackage/manifest.json
> +      "configurationUrl": "https://c867-116-75-13-29.ngrok.io/config",
Can't we add placeholder for domain name?

2022-07-03 12:42 UTC, ChetanSharma-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/public/index.html
> +      content="Web site created using create-react-app"
We can change the content as per the project title.

2022-07-03 12:44 UTC, ChetanSharma-msft requested changes
One cosmetic comment.

2022-07-03 12:44 UTC, ChetanSharma-msft commented on samples/meetings-live-code-interview/nodejs/ClientApp/public/index.html
> +      content="Web site created using create-react-app"
We can change the content as per the project title.

2022-07-03 13:02 UTC, Wajeed-msft approved these changes
Could you please mention Live Share SDK in ReadMe file? This would be similar to C# project.

2022-07-03 16:19 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-03 16:20 UTC, merged