Changes for integrating live share sdk in live-coding c# sample
OfficeDev/Microsoft-Teams-Samples pull request #388
Opened 2022-07-01 13:15 UTC by Prithvi-MSFT

2022-07-02 11:38 UTC, ChetanSharma-msft requested changes
Added my comment

2022-07-02 11:38 UTC, ChetanSharma-msft commented on samples/meetings-live-code-interview/csharp/MeetingLiveCoding/ClientApp/public/index.html
> +      content="Web site created using create-react-app"
We can change this content.

2022-07-02 11:43 UTC, ChetanSharma-msft commented on samples/meetings-live-code-interview/csharp/README.md
>  - [Ngrok](https://ngrok.com/download) (For local environment testing) Latest (any other tunneling software can also be used)
We can change header/title of readme file as
"This sample demos a live coding in a teams meeting stage using live share SDK."

Also, can add doc links of live share sdk in further reading section.

2022-07-02 13:21 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving the PR.

2022-07-03 12:59 UTC, Wajeed-msft approved these changes

2022-07-03 12:59 UTC, Wajeed-msft commented on samples/meetings-live-code-interview/csharp/README.md
> +This sample demos a live coding in a teams meeting stage using live share SDK. In side panel there is a list of question in specific coding language and on share click specific question with language
```suggestion
This sample demos a live coding in a Teams meeting stage using [Live Share SDK](https://aka.ms/livesharedocs). In side panel there is a list of question in specific coding language and on share click specific question with language code editor will be shared with other participant in meeting.
```

2022-07-03 13:22 UTC, merged