Meeting stage view nodejs -> React -> Live share SDK
OfficeDev/Microsoft-Teams-Samples pull request #391
Opened 2022-07-02 20:16 UTC by HunaidHanfee-MSFT

2022-07-03 06:38 UTC, AbhijeetThakur-msft approved these changes

2022-07-03 06:52 UTC, ChetanSharma-msft requested changes
Reviewed and added my comments.

2022-07-03 06:52 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/ClientApp/public/index.html
> +      content="Web site created using create-react-app"
Can we change content?

2022-07-03 06:52 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/ClientApp/src/components/app-in-meeting.jsx
> +    // shareToStage.
Add proper summary

2022-07-03 19:58 UTC, HunaidHanfee-MSFT commented on samples/meetings-stage-view/nodejs/ClientApp/public/index.html
> +      content="Web site created using create-react-app"
Updated

2022-07-03 19:58 UTC, HunaidHanfee-MSFT commented on samples/meetings-stage-view/nodejs/ClientApp/src/components/app-in-meeting.jsx
> +    // shareToStage.
Added

2022-07-03 20:11 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-04 07:53 UTC, Wajeed-msft approved these changes

2022-07-04 07:54 UTC, merged