Meeting stage view C#-> React -> Live share SDK
OfficeDev/Microsoft-Teams-Samples pull request #394
Opened 2022-07-03 19:38 UTC by HunaidHanfee-MSFT

2022-07-03 19:45 UTC, ChetanSharma-msft requested changes
Added my comments

2022-07-03 19:45 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/app-in-meeting.jsx
> +            if (err) {
One line space before starting if

2022-07-03 19:45 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/configure.jsx
> +                saveEvent.notifySuccess();
Add proper line break and spacing.

2022-07-03 19:45 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/configure.jsx
> +                    <input type="radio" name="notificationType" value="Create" onClick={onClick}/> Add hun in a meeting
hun ?

2022-07-03 19:45 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/doing.jsx
> +
Remove empty extra line

2022-07-03 19:45 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/doing.jsx
> +    }
Add proper line break and spacing.

2022-07-03 19:45 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/done.jsx
> +        return elements;
Add proper line break and spacing

2022-07-03 20:13 UTC, HunaidHanfee-MSFT commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/done.jsx
> +        return elements;
Done

2022-07-03 20:13 UTC, HunaidHanfee-MSFT commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/doing.jsx
> +    }
Done

2022-07-03 20:19 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-04 07:54 UTC, Wajeed-msft approved these changes

2022-07-05 06:48 UTC, merged