Added OnBehalf of code to inlcude image of sender in content bubble (C#)
OfficeDev/Microsoft-Teams-Samples pull request #399
Opened 2022-07-11 13:47 UTC by Prithvi-MSFT

2022-07-13 09:27 UTC, ChetanSharma-msft requested changes
Added a comment, please check.

2022-07-13 09:27 UTC, ChetanSharma-msft commented on samples/meetings-content-bubble/csharp/ContentBubble/Bots/ContentBubbleBot.cs
> +                    var behalfData = new OnBehalfOf { ItemId = 0, MentionType = "person", Mri = turnContext.Activity.From.Id, DisplayName = turnContext.Activity.From.Name};
Are we using this variable?

2022-07-13 09:32 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-14 06:25 UTC, Wajeed-msft approved these changes

2022-07-14 06:34 UTC, merged