Added video capability to capture video using selectMedia api
OfficeDev/Microsoft-Teams-Samples pull request #401
Opened 2022-07-18 04:29 UTC by Prithvi-MSFT

2022-07-18 09:32 UTC, ChetanSharma-msft requested changes
Reviewed and provided my comments.

2022-07-18 09:32 UTC, ChetanSharma-msft commented on samples/tab-device-permissions/nodejs/src/components/CaptureVideo.tsx
> + */
We can add a single line comment like below:
// The 'CaptureVideo' component of your app.

2022-07-19 09:50 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-26 16:32 UTC, Wajeed-msft approved these changes

2022-07-27 09:47 UTC, merged