Meeting-token migrated to use Live Share SDK - C#
OfficeDev/Microsoft-Teams-Samples pull request #402
Opened 2022-07-18 22:28 UTC by HunaidHanfee-MSFT

2022-07-19 13:56 UTC, ChetanSharma-msft requested changes
Reviewed and provided my comments.

2022-07-20 13:09 UTC, HunaidHanfee-MSFT commented on samples/meetings-token-app/csharp/ClientApp/src/Context/TeamsContextProvider.js
> +                console.log(context);
Not as required. So, I have removed it.

2022-07-20 13:12 UTC, HunaidHanfee-MSFT commented on samples/meetings-token-app/csharp/ClientApp/src/Components/TabConfig.js
> + * The 'Config' component is used to display your group tabs
Changed to Meeting Tabs

2022-07-21 07:03 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-07-28 05:01 UTC, Wajeed-msft approved these changes

2022-07-28 09:35 UTC, merged