Bot using Sharepoint List : csharp
OfficeDev/Microsoft-Teams-Samples pull request #42
Opened 2021-03-03 06:01 UTC by Trinetra-MSFT

## Description 

This app demonstrates how a bot communicates in teams and stores the conversation data in SharePoint List.
Bot uses the a SharePoint App to perform the `CRUD `operations in the SharePoint List

**language used:**  C#

## Testing
**Upload the custom app in Teams**
![image](https://user-images.githubusercontent.com/50989436/109759882-c36f3480-7c13-11eb-9a38-e69d2c7139e7.png)

**Interaction with the Bot**
![image](https://user-images.githubusercontent.com/50989436/109759972-eb5e9800-7c13-11eb-9246-e8fa02fbef64.png)

**Ping the Bot**
![image](https://user-images.githubusercontent.com/50989436/109760014-fe716800-7c13-11eb-932d-9c692d4a67ae.png)

2021-03-08 11:26 UTC, Wajeed-msft requested changes

2021-03-08 11:26 UTC, Wajeed-msft commented on samples/bot-sharepoint-list/csharp/SPFx_Bot/teamsAppManifest/manifest.json
> +        "id": "00000003-0000-0ff1-ce00-000000000000",
webApplicationInfo is not needed. Please remove.

2021-03-08 11:26 UTC, Wajeed-msft commented on samples/bot-sharepoint-list/csharp/SPFx_Bot/teamsAppManifest/manifest.json
> +            "scopes": [
staticTabs are not required. Please delete.

2021-03-08 11:26 UTC, Wajeed-msft commented on samples/bot-sharepoint-list/csharp/SPFx_Bot/Repositories/SharepointRepository.cs
> +        }
Please add new line after function call. Check other classes and make same changes.

2021-03-08 11:26 UTC, Wajeed-msft commented on samples/bot-sharepoint-list/csharp/SPFx_Bot/Bots/SpfxBot.cs
> +    public class SpfxBot : ActivityHandler
Please rename this to SharePointListBot. 
SPFx is a page and web part model that provides full support for client-side SharePoint development We are just using SharePoint list.

2021-03-08 11:26 UTC, Wajeed-msft commented on README.md
> +|9| Bot using Sharepoint List | This app demonstrate how a Bot saves data in sharepoint list | [View][bot-sharepoint-list#cs] | [View]() | [View]() |
Could you please move this under https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-trkum/SPFxbot#additional-samples?

2021-03-09 17:42 UTC, Wajeed-msft approved these changes

2021-03-19 19:22 UTC, asnow003 approved these changes

2021-03-20 04:52 UTC, merged

2021-03-20 04:52 UTC, Trinetra-MSFT commented
Merging this Pull Request as changes are approved