Teams app | Resource hub
OfficeDev/Microsoft-Teams-Samples pull request #464
Opened 2022-09-14 11:05 UTC by v-haalam

All the help you need to use Teams, all in one place. Get up and running with just the basics, dive into popular topics, master features designed for your work style or industry, get answers to frequently asked questions, and see what’s new.

Client app pages designed in react js.
Backend code integration developed in c# and .net core 6 framework.

2022-09-15 07:13 UTC, Wajeed-msft requested changes
1. Rename the folder as  Microsoft-Teams-Samples/samples/**msteams-application-resourcehub**
2. Update the [ReadMe file](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/v-haalam/resourcehub/samples/app-resourcehub/csharp/README.md) with documentation, deployment guide, solution overview. Ex: [Microsoft-Teams-Samples/samples/msteams-application-qbot](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msteams-application-qbot#qbot). Also include screenshot which will showcase your solution. 
3. Add metadata for sample code discovery:
	a. Add page type YML metadata
Ex: [Microsoft-Teams-Samples/samples/msteams-application-qbot at main · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msteams-application-qbot)

![image](https://user-images.githubusercontent.com/31851992/190338824-89a25cdd-e4ef-4f9f-bbbe-ba3097f3bffc.png)
b. Include sample.json under assets folder.
Ex: [Microsoft-Teams-Samples/sample.json at main · OfficeDev/Microsoft-Teams-Samples (github.com)](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msteams-application-qbot/assets/sample.json)

2022-09-19 06:43 UTC, v-haalam commented
> sample

Resolved all comments

2022-09-27 06:45 UTC, Wajeed-msft approved these changes

2022-09-27 12:48 UTC, vin-vija approved these changes

2022-10-10 09:27 UTC, Wajeed-msft commented on samples/msteams-application-resourcehub/README.md
> + createdDate: "19-09-2022 12:00 PM"
```suggestion
 createdDate: "10/10/2022 02:56:00 PM"
```

2022-10-10 09:28 UTC, Wajeed-msft approved these changes

2022-10-11 04:55 UTC, Prithvi-MSFT approved these changes
Approved

2022-10-11 05:14 UTC, merged