Change Notification Team/Channel Nodejs
OfficeDev/Microsoft-Teams-Samples pull request #471
Opened 2022-09-18 16:36 UTC by Mohammed-MSFT

Hi @ChetanSharma-msft, Raised PR for Change Notification for team/channel please review and add your comments.

2022-09-19 19:31 UTC, ChetanSharma-msft requested changes
Added my comments.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/.env
> +CertificateThumbprint= ""
Check if all of these required and also added the details in Readme file.
What exact values we need to provide here in Readme file.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> + createdDate: "25-08-2022 04:30:15"
This date is wrong.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +   - `Channel.ReadBasic.All`,`ChannelSettings.Read.All`,`Directory.ReadWrite.All`,`Group.ReadWrite.All`
Do we need all of these permissions ?

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +  - Press `F5` to run the project
Node sample will not run using F5 I think,
Please check the steps in another sample.

We need to install the packages etc...
Refer another NodeJS sample's Readme

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +3. You should be having Base64EncodedCertificate and CertificateThumbprint value from *Create and install Self-Signed certificate* step.
Check if you have mentioned all the appsettings key's here with details to get the values.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +1. Fill any GUID for <APP-ID>. You can also put your MicrosoftAppId here.
<Manifest ID>

Manifest ID

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/Manifest/manifest.json
> +    "id": "<<APP ID>>",
MICROSOFT-APP-ID

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/.env
> +MicrosoftAppId = "<<App ID>>"
MICROSOFT-APP-ID

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/package.json
> +    "xlsx": "^0.18.5"
Check if we are using all of these packages.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/package.json
> +    "xlsx": "^0.18.5"
If not, remove

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/components/channelnotification.jsx
> +// <copyright file="dashboard.jsx" company="Microsoft Corporation">
File name is different and here it's different.
Rename it as channel-notification.jsx

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/components/teamnotification.jsx
> +// <copyright file="dashboard.jsx" company="Microsoft Corporation">
File name is different and here it's different.
Rename it as team-notification.jsx

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/index.css
> +  height: 80vh;
Check if we are using all of these CSS

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/index.css
> +  height: 80vh;
If not, remove.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/models/dashboard-state.js
> +}
Why do we need this file ?

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/models/dashboard-state.js
> +}
If we are using it, rename it properly

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/style/card.css
> +
Remove if we are not using all of these CSS

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/style/style.css
> +.input-fields-label {
Remove if we are not using all of these CSS

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/package.json
> +    "start": "node server.js"
Why do we have 2 package.json and 2 package-lock.json ??

Remove one which is not in use.

2022-09-19 19:31 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/server.js
> +});
Is this port number correct ?
Generally we are mentioning 3978 around.
Refer any other sample to clarify it.

2022-09-21 05:18 UTC, ChetanSharma-msft requested changes
Added my review comments

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/Assests/sample.json
> +      },
This is not a csharp sample, kindly update these as per NodeJS sample.

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/Assests/sample.json
> +        "url": "https://raw.githubusercontent.com/OfficeDev/Microsoft-Teams-Samples/v-mfurquan/graph-change-notification-team-channel-nodejs/samples/graph-change-notification-team-channel-nodejs/node
This url should not contain the path of your branch "v-mfurquan"
It should be main branch.

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/Assests/sample.json
> +        "alt": "Solution UX showing Graph Change Notification Team/Channel nodejs"
Update it as "Graph Change Notification For Team/Channel using NodeJs"

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/.env
> +PRIVATE_KEY_PATH=<<Keypath>>
Check if we have added description or how to get this value in ReadMe file.

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +   ```Base64EncodedCertificate```, ```EncryptionCertificateId```, ```PRIVATE_KEY_PATH```
Mention the steps, how to get these values.

```Base64EncodedCertificate```, ```EncryptionCertificateId```, ```PRIVATE_KEY_PATH```

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +1. Provide MicrosoftAppId, MicrosoftAppPassword and MicrosoftAppTenantId in the .env that is created in Azure.
Provide MicrosoftAppId, MicrosoftAppPassword and MicrosoftAppTenantId in the .env that is created in previous step while doing App Registration.

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +## Instruction for .env
I think, this steps should come along with the this step
Update configuration with the ```MicrosoftAppId```, ```MicrosoftAppPassword```, ```MicrosoftAppTenantId```,
   ```Base64EncodedCertificate```, ```EncryptionCertificateId```, ```PRIVATE_KEY_PATH```

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +1. Fill any GUID for <APP-ID>. You can also put your MicrosoftAppId here.
You haven't updated it.

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/client/src/components/channelnotification.jsx
> +    ///Summary///
Is this the correct way of providing summary ?

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/server.js
> +    console.log('app listening on port 3000!');
No updates on this ?

2022-09-21 05:18 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +page_type: sample
Make sure that you have linked this project with main readme file which is present at the root folder.

2022-09-21 09:26 UTC, ChetanSharma-msft requested changes
Added my comments.

2022-09-21 09:26 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/Assests/sample.json
> +        "alt": "Graph Change Notification Team/Channel using Nodejs"
Graph Change Notification for Team/Channel using NodeJS

2022-09-21 09:26 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/helper/certHelper.js
> +
Remove empty extra link

2022-09-21 09:26 UTC, ChetanSharma-msft commented on samples/graph-change-notification-team-channel-nodejs/nodejs/helper/certHelper.js
> +// Licensed under the MIT License.
Also this file name should be like "certificate-helper.js"

2022-09-21 09:33 UTC, ChetanSharma-msft requested changes
Added comments

2022-09-26 06:45 UTC, Prithvi-MSFT reviewed
Added my comments

2022-09-26 06:45 UTC, Prithvi-MSFT commented on samples/graph-change-notification-team-channel-nodejs/nodejs/.env
> +PRIVATE_KEY_PATH=<<Keypath>>
Changes this to PRIVATE_KEY_PATH=<<PrivateKeyFileName>>

2022-09-26 06:45 UTC, Prithvi-MSFT commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +3. Follow this documentation for the steps - [**Create and install Self-Signed certificate**](Certificate Documentation/README.md)
This link is broken

2022-09-26 06:45 UTC, Prithvi-MSFT commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +3. You should be having Base64EncodedCertificate and CertificateThumbprint value from *Create and install Self-Signed certificate* step.
Thumbprint value is not required you can remove that

2022-09-26 06:45 UTC, Prithvi-MSFT commented on samples/graph-change-notification-team-channel-nodejs/nodejs/README.md
> +4. Use Certificate "PEM" format and add path in this way "PRIVATE_KEY_PATH=PathName.pem" in .env file.
Refer this sample and add similar steps for configuring certificates
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/v-pritka/meeting-notification-nodejs/samples/graph-meeting-notification/nodejs

2022-09-26 06:45 UTC, Prithvi-MSFT commented on samples/graph-change-notification-team-channel-nodejs/nodejs/.env
> +CertificateThumbprint= "<<Certificate Thumbprint>>",
Is thumbprint required ? Remove if not needed

2022-09-26 06:46 UTC, Prithvi-MSFT commented
Change the project folder name from **graph-change-notification-team-channel-nodejs** to **graph-change-notification-team-channel**

2022-10-03 05:24 UTC, Prithvi-MSFT approved these changes

2022-10-03 05:54 UTC, Wajeed-msft approved these changes

2022-10-03 05:54 UTC, Wajeed-msft commented on samples/graph-change-notification-team-channel/nodejs/Assests/sample.json
> +    "creationDateTime": "2022-09-19",
Change to latest date.

2022-10-03 05:59 UTC, Wajeed-msft commented on samples/graph-change-notification-team-channel/nodejs/README.md
> + createdDate: "19-09-2022 01:30:15"
```suggestion
 createdDate: "10-03-2022 11:30:15 AM"
```

2022-10-05 17:48 UTC, merged