Updated graph teams tag sample to use delegated permissions
OfficeDev/Microsoft-Teams-Samples pull request #589
Opened 2022-11-23 09:55 UTC by Prithvi-MSFT

2022-11-28 10:14 UTC, ChetanSharma-msft requested changes
Added my review comments.

2022-11-28 10:14 UTC, ChetanSharma-msft commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Controllers/TeamTagController.cs
> +        private readonly IHttpContextAccessor _httpContextAccessor;
Add summary for these.

2022-11-28 10:14 UTC, ChetanSharma-msft commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Helper/GraphHelper.cs
> +                var teamwTagDto = new TeamTag
Rename it as "teamTag"

2022-11-28 10:14 UTC, ChetanSharma-msft commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Provider/SimpleBetaGraphClient.cs
> +        private static readonly string TenantIdConfigurationSettingsKey = "AzureAd:TenantId";
Add summary for these.

2022-11-28 10:14 UTC, ChetanSharma-msft commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Program.cs
>  {
Please push latest appsettings.json

2022-11-28 10:41 UTC, Prithvi-MSFT commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Provider/SimpleBetaGraphClient.cs
> +        private static readonly string TenantIdConfigurationSettingsKey = "AzureAd:TenantId";
Added

2022-11-28 10:41 UTC, Prithvi-MSFT commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Controllers/TeamTagController.cs
> +        private readonly IHttpContextAccessor _httpContextAccessor;
Added

2022-11-28 10:41 UTC, Prithvi-MSFT commented on samples/graph-teams-tag/csharp/GraphTeamsTag/Program.cs
>  {
Added latest app settings

2022-11-28 10:49 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving the PR.

2022-12-02 10:18 UTC, Wajeed-msft approved these changes

2022-12-04 11:54 UTC, ChetanSharma-msft commented
**Executed build pipeline:** https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3613115369
**Result:**

2022-12-05 06:36 UTC, Prithvi-MSFT commented
Build pipeline status - All builds passed
![image](https://user-images.githubusercontent.com/87962396/205565496-ed843a62-c24c-401a-82e7-662ed7011ad8.png)
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3617265065

2022-12-05 06:38 UTC, merged