Share to meeting in stage view sample
OfficeDev/Microsoft-Teams-Samples pull request #622
Opened 2022-12-13 04:50 UTC by Prithvi-MSFT

2022-12-13 05:19 UTC, Pawan-MSFT approved these changes
looks correct, approving.

2022-12-15 13:18 UTC, Pawan-MSFT approved these changes
looks correct, Approving.

2022-12-20 10:20 UTC, ChetanSharma-msft requested changes
Added my review comments.

2022-12-20 10:20 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/share-to-meeting.jsx
> +		</div>
Code alignment doesn't looks correct.

2022-12-20 10:20 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/router/router.js
>                      <Route path="/home" element={<Home />}/>
Looks like Spacing is not correct, please check once ?
{element={<ShareToMeeting />}   

element= { <ShareToMeeting /> }

2022-12-22 13:38 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-12-26 05:07 UTC, Wajeed-msft approved these changes

2022-12-26 06:43 UTC, ChetanSharma-msft commented
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3779646685
Status:

2022-12-27 16:22 UTC, ChetanSharma-msft commented
Executed build pipeline again: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3788668817

2022-12-27 16:36 UTC, merged