Share to meeting in stage view sample nodejs
OfficeDev/Microsoft-Teams-Samples pull request #623
Opened 2022-12-13 09:52 UTC by Prithvi-MSFT

2022-12-15 13:15 UTC, Pawan-MSFT approved these changes
looks correct, Approving

2022-12-20 10:27 UTC, ChetanSharma-msft requested changes
Added my review comments.

2022-12-20 10:27 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/csharp/AppInMeeting/ClientApp/src/components/share-to-meeting.jsx
> +		</>
Please check the content alignment.

2022-12-20 10:27 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/ClientApp/src/components/share-to-meeting.jsx
> +		</>
Please check if this alignment is correct.

2022-12-20 10:27 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/ClientApp/src/router/router.js
>                      <Route path="/home" element={<Home />}/>
Looks like Spacing is not correct, please check once ?
`element={<ShareToMeeting />}`

`element= { <ShareToMeeting /> }`

2022-12-20 10:27 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/Readme.md
> +5) On line 41, replace `<<App id>>` with `Id` obtained in step 3.
Check if line 41 is correct?

2022-12-20 10:27 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/Readme.md
> +8) On line 26, replace `<<Application-ID>>` with `Id` obtained in step 3.
Check this line no as well.
I would suggest, not to specify any line number.

2022-12-22 13:41 UTC, ChetanSharma-msft approved these changes
Approved with suggestions.

2022-12-22 13:41 UTC, ChetanSharma-msft commented on samples/meetings-stage-view/nodejs/Readme.md
> +
Please check if you have added further reading section in it.

2022-12-26 05:08 UTC, Wajeed-msft approved these changes

2022-12-26 06:45 UTC, ChetanSharma-msft commented
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3779653238
Status:

2022-12-27 09:27 UTC, merged