Java and python have been added to the Build complete samples yml file
OfficeDev/Microsoft-Teams-Samples pull request #631
Opened 2022-12-15 16:24 UTC by Harikrishnan-MSFT

2022-12-16 05:32 UTC, Pawan-MSFT approved these changes
looks correct, approving.

2022-12-20 09:38 UTC, ChetanSharma-msft commented on .github/workflows/build-complete-samples.yml
> +      matrix:
@Harikrishnan-MSFT - If you have already run this pipeline, please add the screenshot of executed pipeline.

2022-12-20 09:40 UTC, ChetanSharma-msft requested changes
Added my comments, please fix.

2022-12-20 09:40 UTC, ChetanSharma-msft commented on .github/workflows/build-complete-samples.yml
> +              name: 'bot-conversation'
@Harikrishnan-MSFT - If you have already run this pipeline, please add the screenshot of executed pipeline.

2022-12-20 09:40 UTC, ChetanSharma-msft commented on .github/workflows/build-complete-samples.yml
> +              version: '3.10.x'
Please add one empty line after every entry.

2022-12-20 09:40 UTC, ChetanSharma-msft commented on .github/workflows/build-complete-samples.yml
> +            - project_path: 'samples/bot-task-module/java'
Please add one empty line after every entry.

2022-12-20 10:14 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2022-12-22 05:10 UTC, Wajeed-msft approved these changes

2022-12-22 13:36 UTC, merged