Conversion Of Bot Task Module with Task Module Tab - Nodejs
OfficeDev/Microsoft-Teams-Samples pull request #648
Opened 2022-12-31 19:41 UTC by Mohammed-MSFT

Images and Readme Need to be update

2023-01-02 10:18 UTC, Pawan-MSFT commented
Executed Build pipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3821761962
![image](https://user-images.githubusercontent.com/117965661/210218379-92fc3dab-5b61-43f1-bb81-c81eb77f4dc9.png)

2023-01-02 10:54 UTC, Pawan-MSFT reviewed
please fix comments

2023-01-02 10:54 UTC, Pawan-MSFT commented on samples/bot-task-module/nodejs/index.js
> +// const express = require("express");
remove commented code

2023-01-02 10:54 UTC, Pawan-MSFT commented on samples/bot-task-module/nodejs/pages/configure.html
> +    });
This should be separate JS. for others also.

2023-01-02 10:54 UTC, Pawan-MSFT commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +    }
This should be separate JS.

2023-01-02 10:54 UTC, Pawan-MSFT commented on samples/bot-task-module/nodejs/README.md
>  1) __*This step is specific to Teams.*__
Gif for App-task-Module missing in readme.

2023-01-02 12:14 UTC, ChetanSharma-msft commented
Executed build pipeline:

2023-01-02 12:19 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/.env
> +BaseUrl="<<BaseUrl>>"
Please remove extra added .gif file:

2023-01-02 12:29 UTC, ChetanSharma-msft requested changes
Added my review comments.

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/.env
> +BaseUrl="<<BaseUrl>>"
![image](https://user-images.githubusercontent.com/59052547/210230374-68c6b977-97fa-4d9d-8591-87acabd3fc5f.png)

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/README.md
> +    - **Edit** the `manifest.json` for `ValidDomain` with base Url domain. E.g. if you are using ngrok it would be `https://1234.ngrok.io` then your domain-name will be `1234.ngrok.io`.
`<<Valid-Domain>>`

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/README.md
> +- [Use task modules from bots](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs)
Remove en-us from these URL's.

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/appPackage/manifest.json
> +      "entityId": "com.microsoft.teams.taskmoduletester",
Give Proper entityId:
com.microsoft.teams.taskmoduletester

taskmodule.statictab

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/pages/CustomForm.html
>      <title>Microsoft Teams Task Module Tester - Custom Form</title>
Microsoft Teams Task Module App

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/pages/configure.html
> +      var radios = document.getElementsByName("tabType");
tabType

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +        PowerAppName: "PowerApp",
Add proper alignment and spacing

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +          var submitHandler = function (err, result) { console.log("Err: ".concat(err, "; Result:  + ").concat(result)); };
Alignment and spacing is not correct.

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +                );
Alignment and spacing

2023-01-02 12:29 UTC, ChetanSharma-msft commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +              microsoftTeams.tasks.startTask(taskInfo_1, submitHandler);
one line space.

2023-01-02 12:32 UTC, ChetanSharma-msft commented
@Mohammed-MSFT - Please execute build pipeline once comments fixes are done.

2023-01-02 12:43 UTC, Pawan-MSFT reviewed
Still showing comments please fix these.

2023-01-02 14:12 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/README.md
> +    - **Edit** the `manifest.json` for `ValidDomain` with base Url domain. E.g. if you are using ngrok it would be `https://1234.ngrok.io` then your domain-name will be `1234.ngrok.io`.
fixed

2023-01-02 14:13 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/README.md
> +- [Use task modules from bots](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs)
fixed

2023-01-02 14:13 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/appPackage/manifest.json
> +      "entityId": "com.microsoft.teams.taskmoduletester",
fixed

2023-01-02 14:14 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/pages/CustomForm.html
>      <title>Microsoft Teams Task Module Tester - Custom Form</title>
fixed

2023-01-02 14:15 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/pages/configure.html
> +      var radios = document.getElementsByName("tabType");
fixed

2023-01-02 14:15 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +        PowerAppName: "PowerApp",
fixed

2023-01-02 14:15 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +          var submitHandler = function (err, result) { console.log("Err: ".concat(err, "; Result:  + ").concat(result)); };
fixed

2023-01-02 14:15 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +                );
fixed

2023-01-02 14:16 UTC, Mohammed-MSFT commented on samples/bot-task-module/nodejs/pages/taskmodule.html
> +              microsoftTeams.tasks.startTask(taskInfo_1, submitHandler);
fixed

2023-01-02 16:29 UTC, ChetanSharma-msft commented
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3823889956

2023-01-02 16:29 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2023-01-03 07:50 UTC, Mohammed-MSFT commented
Build Pipeline Executed : https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3823936899
<img width="782" alt="image" src="https://user-images.githubusercontent.com/109147706/210317464-2af20c98-1299-4afd-a1bb-a74e5cfd6917.png">

2023-01-03 08:48 UTC, Wajeed-msft approved these changes

2023-01-03 12:08 UTC, Mohammed-MSFT commented
Executed Build Pipeline After Merge Conflicts Resolved : https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3829237176

<img width="923" alt="image" src="https://user-images.githubusercontent.com/109147706/210354387-6311ef2f-7445-4898-81c2-4ca6adc0feb5.png">

2023-01-03 12:12 UTC, merged