Converted Auth samples to use auth grant flow instead of implicit grant flow
OfficeDev/Microsoft-Teams-Samples pull request #649
Opened 2023-01-01 12:42 UTC by Prithvi-MSFT

2023-01-02 05:21 UTC, ChetanSharma-msft commented
Execute Build Pipeline:

2023-01-02 09:59 UTC, Pawan-MSFT commented
Executed Build Pipeline:
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3821665809

Result:
![image](https://user-images.githubusercontent.com/117965661/210216628-adcd0587-d12c-424a-bb74-8a3063d7e953.png)

2023-01-02 12:34 UTC, ChetanSharma-msft commented
@Prithvi-MSFT - Please execute build pipeline once comments fixes are done.

2023-01-02 13:01 UTC, ChetanSharma-msft requested changes
Added my review comments on your PR.

2023-01-02 13:07 UTC, ChetanSharma-msft commented
Execute build pipeline:

2023-01-02 15:56 UTC, Prithvi-MSFT commented
Build Pipeline status  - All builds passed.
![image](https://user-images.githubusercontent.com/87962396/210254531-8616e986-7057-419e-a703-723e4e363d04.png)

2023-01-02 16:20 UTC, ChetanSharma-msft requested changes
Added my review comments.

2023-01-02 16:20 UTC, ChetanSharma-msft commented on samples/app-complete-auth/csharp/AppCompleteAuth/Pages/auth-end.cshtml.cs
> +        public authEnd(IConfiguration configuration)
Summary alignment is not looks correct.

2023-01-02 16:20 UTC, ChetanSharma-msft commented on samples/app-complete-auth/csharp/AppCompleteAuth/Pages/auth-start.cshtml.cs
> +		/// </summary>
Summary alignment doesn't looks correct.

2023-01-02 16:20 UTC, ChetanSharma-msft commented on samples/tab-staggered-permission/csharp/StaggeredPermission/Pages/auth-end.cshtml.cs
> +        }
Summary alignment doesn't looks correct.

2023-01-02 16:20 UTC, ChetanSharma-msft commented on samples/tab-staggered-permission/csharp/StaggeredPermission/Pages/auth-start.cshtml.cs
>          public void OnGet()
Summary alignment doesn't looks correct.

2023-01-02 16:31 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving the PR.

2023-01-03 04:53 UTC, Pawan-MSFT approved these changes
looks fine, approving!

2023-01-03 07:30 UTC, Wajeed-msft approved these changes

2023-01-03 09:23 UTC, Prithvi-MSFT commented
Build pipeline status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/3828140072

![image](https://user-images.githubusercontent.com/87962396/210329886-ff2f1022-7ca3-4883-8d6b-678bfcb3229e.png)

2023-01-03 09:30 UTC, merged