MetaOS readme changes and issue fixes
OfficeDev/Microsoft-Teams-Samples pull request #681
Opened 2023-01-20 18:21 UTC by Pawan-MSFT

2023-01-25 12:20 UTC, ChetanSharma-msft requested changes
Added my review comments.

2023-01-25 12:20 UTC, ChetanSharma-msft commented on samples/app-complete-sample/csharp/manifest_hub/manifest_hub.json
> +      "botId": "{{Microsoft-App-Id}}",
Remove these sections.

2023-01-25 12:20 UTC, ChetanSharma-msft commented on samples/app-complete-sample/nodejs/Manifest_hub/manifest.json
> +  "configurableTabs": [
Remove configurable tab and bots

2023-01-25 12:20 UTC, ChetanSharma-msft commented on samples/tab-personal/mvc-csharp/Manifest_Hub/manifest.json
> +    "websiteUrl": "https://6dd4-14-142-36-202.ngrok.io",
Please update these URls

2023-01-25 12:20 UTC, ChetanSharma-msft commented on samples/tab-personal/mvc-csharp/Manifest_Hub/manifest.json
> +      "contentUrl": "https://6dd4-14-142-36-202.ngrok.io/PersonalTab",
Please update these URls

2023-01-25 12:21 UTC, ChetanSharma-msft commented
Please run build pipeline.

2023-01-25 12:31 UTC, Pawan-MSFT commented on samples/app-complete-sample/csharp/manifest_hub/manifest_hub.json
> +      "botId": "{{Microsoft-App-Id}}",
Fixed

2023-01-25 12:31 UTC, Pawan-MSFT commented on samples/tab-personal/mvc-csharp/Manifest_Hub/manifest.json
> +    "websiteUrl": "https://6dd4-14-142-36-202.ngrok.io",
Fixed

2023-01-25 12:31 UTC, Pawan-MSFT commented on samples/tab-personal/mvc-csharp/Manifest_Hub/manifest.json
> +      "contentUrl": "https://6dd4-14-142-36-202.ngrok.io/PersonalTab",
Fixed

2023-01-25 13:14 UTC, Pawan-MSFT commented
**Execute build pipeline:** 
[https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4005963631
Result:](https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4005963631)

2023-01-26 09:39 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving the PR.

2023-01-27 14:22 UTC, ChetanSharma-msft commented
Execute build pipeline:

2023-01-30 10:16 UTC, Wajeed-msft approved these changes

2023-01-30 18:44 UTC, merged