Samples readme updated to include features description
OfficeDev/Microsoft-Teams-Samples pull request #731
Opened 2023-03-03 18:19 UTC by Prithvi-MSFT

2023-03-06 06:08 UTC, Pawan-MSFT reviewed
Please fix comments

2023-03-06 06:08 UTC, Pawan-MSFT commented on samples/graph-channel-lifecycle/nodejs/Readme.md
> +* Graph API
can we merge these into single heading.

2023-03-06 06:08 UTC, Pawan-MSFT commented on samples/graph-pinned-messages/csharp/README.md
> +* Teams SSO (Tabs)
make consistent.

2023-03-06 14:31 UTC, Pawan-MSFT approved these changes
looks correct approving.

2023-03-24 06:20 UTC, Wajeed-msft requested changes

2023-03-24 10:50 UTC, Wajeed-msft approved these changes

2023-04-02 18:57 UTC, Prithvi-MSFT commented
Build status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4590222204

2023-04-02 19:00 UTC, merged