Bot-formatting-card issue fixes
OfficeDev/Microsoft-Teams-Samples pull request #779
Opened 2023-04-19 13:27 UTC by Pawan-MSFT

2023-04-24 12:03 UTC, ChetanSharma-msft requested changes
Added my review comments

2023-04-24 12:14 UTC, Pawan-MSFT commented on samples/bot-formatting-cards/csharp/BotFormattingCards/Bots/DialogBot.cs
> +                var attachments = new List<Attachment>();
Fixed

2023-04-24 12:14 UTC, Pawan-MSFT commented on samples/bot-formatting-cards/csharp/BotFormattingCards/Cards/AllCards.cs
> +            var adaptiveCardJson = System.IO.File.ReadAllText(Path.Combine(paths));
Fixed

2023-04-26 05:24 UTC, ChetanSharma-msft approved these changes
Looks fine, approving it.

2023-04-26 09:30 UTC, Wajeed-msft approved these changes

2023-04-27 10:22 UTC, Pawan-MSFT commented
Executed build pipeline
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/4818666831

2023-04-27 10:38 UTC, merged