bot-proactive message sample migration
OfficeDev/Microsoft-Teams-Samples pull request #787
Opened 2023-04-27 05:14 UTC by Prithvi-MSFT

2023-04-28 12:43 UTC, ChetanSharma-msft requested changes
Added my reviews

2023-04-28 12:43 UTC, ChetanSharma-msft commented on samples/bot-proactive-messaging-teamsfx/teamsapp.yml
> +projectId: 8e391fef-aec7-4502-a048-4033ad57210c
Do we need to hardcode ?

2023-05-04 05:38 UTC, HuihuiWu-Microsoft commented on samples/bot-proactive-messaging-teamsfx/teamsapp.yml
> +projectId: 8e391fef-aec7-4502-a048-4033ad57210c
Better remove the field.

2023-05-04 05:43 UTC, HuihuiWu-Microsoft commented on samples/bot-proactive-messaging-teamsfx/env/.env.dev
Please also include .env.local file

2023-05-04 10:51 UTC, Prithvi-MSFT commented on samples/bot-proactive-messaging-teamsfx/teamsapp.yml
> +projectId: 8e391fef-aec7-4502-a048-4033ad57210c
Removed the field

2023-05-05 02:10 UTC, HuihuiWu-Microsoft approved these changes

2023-05-05 02:12 UTC, Wajeed-msft approved these changes

2023-05-05 02:14 UTC, merged