Added changes to include deeplink to meeting side panel
OfficeDev/Microsoft-Teams-Samples pull request #801
Opened 2023-05-16 20:40 UTC by Prithvi-MSFT

2023-05-17 11:40 UTC, ChetanSharma-msft requested changes
Added my review comments

2023-05-17 11:40 UTC, ChetanSharma-msft commented on samples/tab-deeplink/csharp/DeepLinkBot/Services/DeeplinkHelper.cs
> +        public string GetDeepLinkToMeetingSidePanel(string teamsUrl, string appID, string baseUrl, string entityId, string chatId, string contextType)
Kindly add method summary.

2023-05-17 11:40 UTC, ChetanSharma-msft commented on samples/tab-deeplink/csharp/DeepLinkBot/Services/DeeplinkHelper.cs
>          public string GetDeepLinkToChannelTask(string teamsUrl, string appID,string baseUrl,string channelId, string entityId, string subEntityID)
Kindly add method summary.

2023-05-19 08:15 UTC, Prithvi-MSFT commented on samples/tab-deeplink/csharp/DeepLinkBot/Services/DeeplinkHelper.cs
> +        public string GetDeepLinkToMeetingSidePanel(string teamsUrl, string appID, string baseUrl, string entityId, string chatId, string contextType)
Added

2023-05-19 08:16 UTC, Prithvi-MSFT commented on samples/tab-deeplink/csharp/DeepLinkBot/Services/DeeplinkHelper.cs
>          public string GetDeepLinkToChannelTask(string teamsUrl, string appID,string baseUrl,string channelId, string entityId, string subEntityID)
added

2023-05-22 09:15 UTC, ChetanSharma-msft commented
@Prithvi-MSFT - Kindly run build pipeline before merging this PR.

2023-05-22 11:41 UTC, Wajeed-msft approved these changes

2023-05-25 05:10 UTC, Prithvi-MSFT commented
Build status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5066762364

2023-05-25 06:54 UTC, merged