Tab device permission sample readme changes
OfficeDev/Microsoft-Teams-Samples pull request #830
Opened 2023-06-14 01:36 UTC by Prithvi-MSFT

2023-06-19 12:50 UTC, ChetanSharma-msft requested changes
Added my review comments

2023-06-19 18:11 UTC, Prithvi-MSFT commented on samples/tab-device-permissions/nodejs/README.md
> +Currently only capture image is supported in Teams Desktop
changed

2023-06-19 18:30 UTC, Prithvi-MSFT commented
Build status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5314966459

2023-06-20 14:15 UTC, ChetanSharma-msft approved these changes
Changes looks fine.

2023-06-21 12:26 UTC, Mohammed-MSFT approved these changes
Changes Looks Fine Approving It.

2023-06-21 12:28 UTC, merged