Tab Stage View META-OS Unfurling Updates
OfficeDev/Microsoft-Teams-Samples pull request #832
Opened 2023-06-14 09:34 UTC by Mohammed-MSFT

Hi @ChetanSharma-msft @Prithvi-MSFT

Raied PR for Tab Stage View META-OS Unfurling Updates

Please review and provide feedback.

Thanks.

2023-06-19 12:39 UTC, ChetanSharma-msft requested changes
Added my review comments.

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/README.md
> +**on the tool bar on top,select Apps icon. Your sideloaded app title appears among your installed apps**
**On the tool bar on top, select Apps icon. Your sideloaded app title appears among your installed apps**

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/README.md
> +**Opening stage view from unfurling link. If you copy and paste a link from https://www.BotFramework.com into the compose message area the link will unfurl.**
**Opening the stage view from unfurling link. If you copy and paste a link from https://www.BotFramework.com into the compose message area the link will unfurl.**

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/microsoft-teams-samples/samples/tab-stage-view-csharp" />
Is this not required?

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/TabInStageView/Bots/ActivityBot.cs
> +        // <summary>
/// <summary>

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/TabInStageView/Bots/ActivityBot.cs
> +            AdaptiveCard card = new AdaptiveCard(new AdaptiveSchemaVersion("1.2"))
Can't we create json for this?
Also, 1.2 is the latest version?

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/TabInStageView/Bots/ActivityBot.cs
> +
Remove extra empty lines.

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/TabInStageView/Manifest/manifest.json
> +      "botId": "{{Microsoft-App-Id or Bot-id}}",
Not consistent placeholder name, check nodejs PR

2023-06-19 12:39 UTC, ChetanSharma-msft commented on samples/tab-stage-view/csharp/TabInStageView/Manifest_Hub/manifest.json
> +      "botId": "{{Microsoft-App-Id or Bot-id}}",
Not consistent placeholder name, check nodejs PR

2023-06-19 12:39 UTC, ChetanSharma-msft commented
@Mohammed-MSFT - Kindly run build pipeline.

2023-06-20 16:09 UTC, Prithvi-MSFT approved these changes

2023-06-22 14:16 UTC, Prithvi-MSFT commented
Build status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5345357148

2023-06-23 05:50 UTC, merged