Fixed tab request approval issue
OfficeDev/Microsoft-Teams-Samples pull request #842
Opened 2023-06-26 14:19 UTC by Harikrishnan-MSFT

2023-06-28 05:54 UTC, ChetanSharma-msft requested changes
Added my review comment

2023-06-28 05:54 UTC, ChetanSharma-msft commented on samples/tab-request-approval/csharp/TabRequestApproval/Views/Home/Index.cshtml
> +                managerName: person[0].scoredEmailAddresses[0].address,
Kindly rename variable as userName or personaName

2023-06-29 07:57 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2023-06-29 10:55 UTC, Prithvi-MSFT commented
Build status  - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5411190102

2023-06-29 10:56 UTC, Prithvi-MSFT approved these changes

2023-06-29 10:56 UTC, merged