Teams fx migration samples
OfficeDev/Microsoft-Teams-Samples pull request #913
Opened 2023-08-16 14:35 UTC by Harikrishnan-MSFT

2023-08-23 04:41 UTC, formulahendry approved these changes

2023-08-23 09:19 UTC, ChetanSharma-msft requested changes
Added few comments

2023-08-23 09:19 UTC, ChetanSharma-msft commented on samples/meeting-recruitment-app/nodejs/Readme.md
> +1. Ensure you have downloaded and installed [Visual Studio Code](https://code.visualstudio.com/docs/setup/setup-overview)
What about deployment steps?

2023-08-23 09:19 UTC, ChetanSharma-msft commented on samples/meeting-recruitment-app/nodejs/appPackage/manifest.json
> +      "configurationUrl": "https://${{BOT_DOMAIN}}:3000/configure",
Why we required 3000??

2023-08-23 12:08 UTC, Harikrishnan-MSFT commented on samples/meetings-token-app/nodejs/Readme.md
>  - [Nodejs](https://nodejs.org/en/download/) version 10.21.0+ (use the LTS version)
Fixed

2023-08-23 12:13 UTC, Harikrishnan-MSFT commented on samples/meeting-recruitment-app/nodejs/Readme.md
> +1. Ensure you have downloaded and installed [Visual Studio Code](https://code.visualstudio.com/docs/setup/setup-overview)
Fixed

2023-08-24 05:29 UTC, ChetanSharma-msft requested changes
Added my review comment

2023-08-24 05:29 UTC, ChetanSharma-msft commented on samples/meeting-recruitment-app/nodejs/Readme.md
> +    Alternatively, you can also use the `dev tunnel`. Please follow [Create and host a Dev tunnel](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows) and host the
Need to update this contents.

2023-08-24 05:31 UTC, Mohammed-MSFT approved these changes
Changes Looks Fine, Approving It.

2023-08-24 10:56 UTC, Harikrishnan-MSFT commented on samples/meeting-recruitment-app/nodejs/Readme.md
> +    Alternatively, you can also use the `dev tunnel`. Please follow [Create and host a Dev tunnel](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows) and host the
Fixed

2023-08-24 11:06 UTC, Harikrishnan-MSFT commented
**Build Pipeline -** 
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/5962805228

![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/117716554/70726660-4950-499f-9257-2eedcb67a712)

2023-08-24 13:32 UTC, Prithvi-MSFT approved these changes

2023-08-28 06:02 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2023-08-28 06:02 UTC, merged