App Catalog Graph LifeCycle using Bot
OfficeDev/Microsoft-Teams-Samples pull request #93
Opened 2021-05-19 08:13 UTC by Trinetra-MSFT

### Description

This sample app shows how to integrate App Catalog Graph API in Bot and utilize the life cycle of an teams app in Catalog.

**Language Used: C#**

### Proposed Changes
1. Covering List Apps in Catalog all scenario
2. Publishing App to Catalog 
3. Update App in Catalog covering sceanrio
4. Delete App in Catalog

### Testing
1. Install App Catalog Bot to teams
2. Ping the Bot
Bot will list out supported Action commands
![image](https://user-images.githubusercontent.com/50989436/118778342-9ee83780-b8a7-11eb-93fc-96bf8448e8e0.png)

- listApps

![image](https://user-images.githubusercontent.com/50989436/118778263-8841e080-b8a7-11eb-8499-5892a05e2922.png)

-listAppById
![image](https://user-images.githubusercontent.com/50989436/118778449-bc1d0600-b8a7-11eb-8370-cdd7564f4cd4.png)

-listBotApps
![image](https://user-images.githubusercontent.com/50989436/118778526-cdfea900-b8a7-11eb-91fc-219b4d79098b.png)

- Publish App to Catalog
![image](https://user-images.githubusercontent.com/50989436/118778589-e2db3c80-b8a7-11eb-8159-a7880be1925e.png)

- Update App in Catalog
![image](https://user-images.githubusercontent.com/50989436/118778655-f1295880-b8a7-11eb-9901-cf10e28c006e.png)

- Delete App from Catalog
![image](https://user-images.githubusercontent.com/50989436/118778780-0f8f5400-b8a8-11eb-8353-386de052f324.png)

- Checking the App status
![image](https://user-images.githubusercontent.com/50989436/118778856-246be780-b8a8-11eb-9dcc-b551f1136ecc.png)

2021-05-26 07:21 UTC, Wajeed-msft requested changes

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +﻿### AppCatalog sample
Could you please add entry for this sample in Root reaadme file?

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +
Let's include reference to setting up auth part of Bot. Link to documentation should be helpful.

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> + - List all applications specific to the tenant : type "listapp" in chat and get all the app available in the same tenant.
Could you please just reference the respective images here?

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/AppCatalog.cs
> +                {
Could you please fix the indentation in all the files?

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/AppCatalog.cs
> +        public static async Task<IList<TeamsApp>> GetAllapp()
This method is causing compilation error as Not all the paths return values. Could you please fix this?

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/AppCatalog.cs
> +  public class AppCatalog
Could you please rename this to AppCatalogHelper?

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/AppCatalog.cs
> +        public string GetToken(string token)
This should be SetToken(). Could you please remove static method and have it as instance property (May be constructor parameter)?

2021-05-26 07:21 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/AppCatalog.cs
> +                GraphClient graphClient = new GraphClient(gToken);
This is repeatative in all the methods. Could you please have single client which is used across?

2021-05-28 11:45 UTC, Wajeed-msft requested changes

2021-05-28 11:45 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +  - Launch Visual Studio
Could you please add instruction on setting connection settings? You can refere to [existing doc](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#azure-ad-v2)  however make sure you specify which permissions are requried.

2021-05-31 17:51 UTC, Wajeed-msft requested changes

2021-05-31 17:51 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/AppCatalog.cs
> +        public static string gToken { get; set; }
Access token can not be static field, this will overlap if multiple users are using this app. Could you please change this to instance filed?

2021-05-31 17:51 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +  - Launch Visual Studio
Marking this as unresolved. Could you please work on this?

2021-06-02 12:23 UTC, Wajeed-msft requested changes

2021-06-02 12:23 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +  B) Or from Visual Studio code
Could you please correct the sequence of steps? This one started with B directly.

2021-06-02 12:23 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +[Provide the connectionstring2 image url here]
Could you please provide actual image instead of just placeholder?

2021-06-02 12:23 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +A) Run ngrok - point to port 3978
This step looks out of place. Could you please fix it? Let's setup this locally once by following steps mentioned in read me and make corrections.

2021-06-02 12:23 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/OAuthHelpers.cs
> +    public static class OAuthHelpers
Not sure why this is called as OAuthHelper, could you please correct the naming for this class?

2021-06-02 12:23 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/Helper/OAuthHelpers.cs
> +        public static async Task<IList<TeamsApp>> AppCatalogById(ITurnContext turnContext, TokenResponse tokenResponse)
Check if these additional wrapper methods are required. I believe you can directly call these instead.

2021-06-02 12:25 UTC, Wajeed-msft commented on samples/graph-appcatalog-lifecycle/csharp/README.md
> +  B) Or from Visual Studio code
Also correct the folder specficied in the step here: 

 **Navigate to `graph-appcatalog-lifecycle/node` folder**
 Expected: 
 **Navigate to `samples/graph-appcatalog-lifecycle/csharp` folder**

2021-06-07 14:14 UTC, Wajeed-msft approved these changes

2021-06-09 14:48 UTC, asnow003 approved these changes

2021-06-09 19:29 UTC, merged