added manifest changes for nodejs samples
OfficeDev/Microsoft-Teams-Samples pull request #945
Opened 2023-09-06 08:47 UTC by Prithvi-MSFT

2023-09-13 10:43 UTC, ChetanSharma-msft approved these changes
Changes looks fine, approving it.

2023-09-13 10:47 UTC, Mohammed-MSFT approved these changes
Approved, Changes looks fine.

2023-09-13 11:16 UTC, Jegadeesh-MSFT approved these changes
changes look good.

2023-09-13 18:30 UTC, ChetanSharma-msft commented
Executed build pipeline: https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6176427767

2023-09-18 08:31 UTC, Prithvi-MSFT commented
Build status - All builds passed
https://github.com/OfficeDev/Microsoft-Teams-Samples/actions/runs/6219931794

2023-09-18 09:02 UTC, merged

2023-09-18 09:11 UTC, ChetanSharma-msft requested changes
added more review comments

2023-09-18 09:11 UTC, ChetanSharma-msft commented on samples/meeting-recruitment-app/nodejs/.gitignore
> +appMAnifest/build
appManifest

2023-09-18 09:11 UTC, ChetanSharma-msft commented on samples/tab-sso/nodejs/README.md
> +    **Note:** If you want to test your app across multi hub like: Outlook/Office.com, please update the `manifest.json` in the `tab-sso\nodejs\Manifest_Hub` folder with the required values.
Please check these:
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/59052547/5a3b8ab4-e47a-4e20-a299-c672253fe7b7)

2023-09-18 09:11 UTC, ChetanSharma-msft commented on samples/tab-stage-view/nodejs/Readme.md
> +   **Note:** If you want to test your app across multi hub like: Outlook/Office.com, please update the `manifest.json` in the `tab-stage-view\nodejs\Manifest_Hub` folder with the required values.
Same here
![image](https://github.com/OfficeDev/Microsoft-Teams-Samples/assets/59052547/bfa66804-191a-4c67-87e6-23c57d90d637)

2023-09-18 09:11 UTC, ChetanSharma-msft commented on samples/tab-staggered-permission/nodejs/README.md
> +    - **Zip** up the contents of the `appManifest` folder to create a `Manifest.zip` or `appManifest_Hub` folder to create a `Manifest_Hub.zip` (Make sure that zip file does not contains any subfolde
This also looks wrong.

2023-09-18 11:22 UTC, Prithvi-MSFT commented
Added changes inside below PR
https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/935#pullrequestreview-1630610155

2023-09-18 11:22 UTC, Prithvi-MSFT commented on samples/tab-staggered-permission/nodejs/README.md
> +    - **Zip** up the contents of the `appManifest` folder to create a `Manifest.zip` or `appManifest_Hub` folder to create a `Manifest_Hub.zip` (Make sure that zip file does not contains any subfolde
changed

2023-09-18 11:22 UTC, Prithvi-MSFT commented on samples/tab-stage-view/nodejs/Readme.md
> +   **Note:** If you want to test your app across multi hub like: Outlook/Office.com, please update the `manifest.json` in the `tab-stage-view\nodejs\Manifest_Hub` folder with the required values.
changed

2023-09-18 11:23 UTC, Prithvi-MSFT commented on samples/tab-sso/nodejs/README.md
> +    **Note:** If you want to test your app across multi hub like: Outlook/Office.com, please update the `manifest.json` in the `tab-sso\nodejs\Manifest_Hub` folder with the required values.
changed

2023-09-18 11:23 UTC, Prithvi-MSFT commented on samples/meeting-recruitment-app/nodejs/.gitignore
> +appMAnifest/build
changed